### ISSUE TITLE
Provider wiki

### ISSUE THREAD

**Issue by qualquervalor** [hapijs/bell#109]
It would be useful if there were a wiki that provided reference material associated with the various providers.  It can be somewhat difficult to track down the documentation about endpoints, scopes, response bodies, etc..  This information has to be researched when creating a provider for the first time, so it couldn't hurt if it was recorded at that time.  This should help in the long run in maintaining the code when the provider updates there service.  Here is a sample associated with the Google provider:

Endpoints:
Goggle discovery doc for the plus service:
https://www.googleapis.com/discovery/v1/apis/plus/v1/rest

Auth and Token Details:
Auth and Token based on values found in the OpenIDConnect discovery document:
https://accounts.google.com/.well-known/openid-configuration

Scopes:
Scope discussion can be found here:
https://developers.google.com/+/web/api/rest/oauth#plus.login

Response body:
Documentation of response body:
https://developers.google.com/+/web/api/rest/latest/people#resource

**Comment by ldesplat** [comment]
What do you think about documenting the provider details directly in the source code of the providers?

It would have more of a chance at staying up to date...

**Comment by qualquervalor** [comment]
I think it would still merit having a significant portion if it outside the code base.  It is easier to diff code changes version to version if there is not a large portion of changing comments sprinkled throughout a file.  Plus some of this type of information could be hard to find if it was dispersed throughout a code base.  Regardless of whether it is put in the code or in a wiki, it will eventually get dated.  If it was in the code would you then not want to accept a pull request if a volunteer submitted code fixes but didn't update the documentation.

**Comment by ldesplat** [comment]
To directly answer your question, I would not accept the PR as is. That's what is done on other Hapi repos.

Now, I would love to better document each provider from a user's perspective. I think that this is not documented currently (spread around the README.md and I am not sure if it is exhaustive). So document, exactly what type of options you can pass to it in a specific section of the README or its own markdown file.

Having a link to the specifics of each implementations, facebook docs, google docs, phabricator docs, ... I could see that being put with that documentation. But I would not summarize that information in here.

Would you be alright with such a solution or is there something I am missing?

**Comment by qualquervalor** [comment]
More documentation in any format would be good, so yes.

**Comment by ldesplat** [comment]
Fixed by #139
