### ISSUE TITLE
5.0.0 google.js example fails

### ISSUE THREAD

**Issue by eloop** [hapijs/bell#118]
With the following error -

"Authentication failed due to: Failed obtaining google user profile"

Can anyone verify the google.js example is working ? Am I doing something wrong ?

-Drew

**Comment by ldesplat** [comment]
You must enable the Google+ API in your profile. Looks like the example comments have not been updated with that extra information.
Go to APIs & Auth, then APIs and under Social APIs click Google+ API and enable it.
I'll happily take a PR that fixes that documentation in the example :)

**Comment by eloop** [comment]
Done. PR #119

**Comment by ldesplat** [comment]
Thanks!
