### ISSUE TITLE
OAuth2's grant_type is fixed to "authorization_code".

### ISSUE THREAD

**Issue by gregnorth** [hapijs/bell#124]
Is there a particular reason grant_type is always "authorization_code"? The ability to override this would be an awesome feature.

**Comment by ldesplat** [comment]
There are 4 different types and the implicit one is mostly applicable to untrusted clients.

The other 2, are just a simple call to the OAuth 2 servers. I would accept a PR that implements it cleanly, but I don't see much value. The authorization_code grant has to do a bit of work, with redirecting and some state management which can be tricky to implement properly and therefore implement securely.

**Comment by ldesplat** [comment]
I am going to close this issue. If you feel strongly about it, feel free to reopen it and I'll keep it there until someone implements it!
