### ISSUE TITLE
FB Auth :- Request.Resource is undefined

### ISSUE THREAD

**Issue by GJ2511** [hapijs/bell#128]
Hi I am trying to use FB auth with bell + hapi.js . I follow all the steps provide in documentation. But when I am hitting the respective route Resource becomes undefined in request,  while it is working fine for my other routes

here is my code

    server.register(require('bell'), function (err) {
           server.auth.strategy('facebook', 'bell', {
                provider: 'facebook',
                password: 'cookie_encryption_password',
               clientId: 'client_id',
               clientSecret: 'client_secret',
               isSecure: false     
    });
 
     server.route({
        method: ['GET', 'POST'], // Must handle both GET and POST 
        path: '/login',          // The callback endpoint registered with the provider 
        config: {
            auth: 'facebook',
            handler: function (request, reply) {
                   return reply.redirect('/home');
            }
        }
    });

and here is my code where I am getting this error:-

    server.ext('onPreResponse', function (req, reply) {
         var ip = req.resources.ip;
    });

I am getting following error when I hit the '/login' route

    Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'ip' of undefined
    at module.exports (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/app.js:88:27)
    at /home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/lib/handler.js:312:22
    at iterate (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at Function.wrapped [as _next] (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/node_modules/hoek/lib/index.js:798:20)
    at Function.internals.continue (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/lib/reply.js:102:10)
    at server.ext.ip (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/app.js:55:30)
    at /home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/lib/handler.js:312:22
    at iterate (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/home/daffo-lap-268/Rockstar/globalrockstar-frontend/node_modules/hapi/node_modules/items/lib/index.js:27:25)

Can any one please help me regarding this issue.

Thanks In advance

**Comment by mtharrison** [comment]
What is `req.resources`?

**Comment by GJ2511** [comment]
This is an object I used to set on preHandler

here for example:-

server.ext('onPreHandler', function(req,res){

req.resources = req.resources || {
ip : "xxx"
};
});

**Comment by mtharrison** [comment]
What's happening is that `onPreHandler` isn't running for your bell route because the auth strategy has already set a response (i.e. the redirect to facebook) so there's no need for a handler.

It you have to decorate the request for every request like that, do it in `onRequest` instead which comes earlier in the request lifecycle and is guaranteed for every request.

Also I would advise against setting your own properties on the `request` object like that, there could be conflicts in the future and it's just bad practice. The `request.app` property exists for storing runtime state. So in short, do this instead:

```javascript
server.ext('onRequest', function (request, reply) {

        request.app.resources = {
            ip: 'xxx.xxx.xxx.xxx'
        };
        reply.continue();
    });
```

**Comment by GJ2511** [comment]
Thanks for your suggestion .... I will try this..

**Comment by GJ2511** [comment]
it is working fine thanks @mtharrison
