### ISSUE TITLE
JWT ?

### ISSUE THREAD

**Issue by sgentile** [hapijs/bell#135]
We are currently using JWT with Hapi, but I want to add in facebook/twitter support - does bell support JWT ?

**Comment by devinivy** [comment]
Are you referring to any particular third-party services that use JWT?  You can always register multiple auth strategies to a given route (using an array of strategy names)– sounds like that might be a nice scenario for you if you already have a strategy that uses JWT and you want to add additional bell strategies.

**Comment by sgentile** [comment]
Thank you perfect - I don't think I realized you can pass an array of strategy names!
