### ISSUE TITLE
OAuth provider is detecting 'socket' instead of 'http' as protocol

### ISSUE THREAD

**Issue by bherila** [hapijs/bell#136]
Consider the following OAuth URL generated by Bell: 

https://www.facebook.com/v2.3/dialog/oauth?client_id=859994797418065&response_type=code&redirect_uri=socket%3A%2F%2Fwebtier.undergroundcellar.com%2Fsignin%2Ffacebook&state=y2uYfM8i97sgrzcAQnn7w6&scope=email

Looking closer, at `redirect_uri` query param, we see the protocol is "socket"

This is coming from here: https://www.facebook.com/v2.3/dialog/oauth?client_id=859994797418065&response_type=code&redirect_uri=socket%3A%2F%2Fwebtier.undergroundcellar.com%2Fsignin%2Ffacebook&state=y2uYfM8i97sgrzcAQnn7w6&scope=email, namely `protocol = request.connection.info.protocol;` 

Does anyone know why this is returning "socket" instead of "http" (here https is not being used). I was thinking of adding this after L153 but it feels like the wrong approach: 

```js
            if (protocol === 'socket') {
                protocol = 'http';
            }
```

Any advice?

Thanks,
Ben
fyi @d-alejo

**Comment by ldesplat** [comment]
What does your route config look like?

**Comment by bherila** [comment]
Route config:
```js
var routes = {
/*...*/
  'signin': {
    path: '/signin',
    method: ['GET', 'POST']
  },
  'oauth': {
    path: '/signin/facebook',
    method: ['GET', 'POST'],
    config: {
      auth: {
        strategy: 'facebook',
        mode: 'required'
      }
    }
  }, /* ... */
```

now there **is** a proxy however it is not on that route: 
```js
exports.routes.push({
  path: '/api/{path*}',
  method: '*',
  handler: {
    proxy: {
      passThrough: true,
      xforward: true,
      localStatePassThrough: true,
      mapUri: function (request, callback) {
        callback(null, __app.env.midtierHostname +
          '/api/' + request.params.path, {});
      }
    }
  }
});
```

and I do process the route in the following way (but do not believe this is leading to the issue)
```js
// match the matching controller to its route
for (var controllerName in routes) {
  // spaces and dashes are converted to underscores for file names
  var controllerFile = path.resolve(__base, './controllers/' + controllerName
      .toLowerCase().replace(/[-\s]/gi, '_'));
  routes[controllerName].handler = require(controllerFile).controller;
  exports.routes.push(routes[controllerName]);
}
```

Entire routes.js if you are so inclined: https://gist.github.com/bherila/6ba0b9be1daa4b220fbe

Thanks again for your help :smile: !

**Comment by ldesplat** [comment]
I asked for the wrong information!

So your routes are not listening to a http or https connection. Maybe, you are using a unix socket for your connection(s)? Maybe you have a reverse proxy configuration and nginx/apache/haproxy or whomever is sending the data that way?

Either way, we should be supporting that mode so it looks like a bug to me. We should be forcing http or https I am pretty sure.

**Comment by ldesplat** [comment]
You are welcome to send a PR.

Probably have to change [L159](https://github.com/hapijs/bell/blob/master/lib/oauth.js#L159) , [L192](https://github.com/hapijs/bell/blob/master/lib/oauth.js#L192) , and [L26](https://github.com/hapijs/bell/blob/master/lib/oauth.js#L26)
Looks like also some code for oauth v1 needs to change.

**Comment by ldesplat** [comment]
You can use `location` option.

location - Set the base redirect_uri manually if it cannot be inferred properly from server settings. Useful to override port, protocol, and host if proxied or forwarded.
