### ISSUE TITLE
not getting email from linkedin

### ISSUE THREAD

**Issue by rajeev37** [hapijs/bell#143]
I am using bell for getting Linkedin detail but i am unable to access email. the response comes from Linkedin are: 
 profile: 
   { id: 'ur6DT0hN6Y',
     name: { first: 'Rajeev', last: 'Thakur' },
     email: undefined,
     headline: 'Ruby On Rails at Swift Setup',
     raw: 
      { firstName: 'Rajeev',
        headline: 'Ruby On Rails at Swift Setup',
        id: 'ur6DT0hN6Y',
        lastName: 'Thakur',
        siteStandardProfileRequest: [Object] } } }

It show email is undefined. On https://www.linkedin.com/developer I checked Default Application Permissions 'r_basicprofile' and 'r_emailaddress'. still it showing undefined email.

**Comment by ldesplat** [comment]
Have you figured it out already?

If not, when you're creating your linked in strategy you can add `scope: ['r_basicprofile', 'r_emailaddress']`. See if that helps.

**Comment by rajeev37** [comment]
@ldesplat  I have already added that scope to linkedin strategy and also update bell version to latest but still it not getting email.

**Comment by ldesplat** [comment]
So, I looked at the documentation for LinkedIn and figured it out.

In your strategy add the following:
```
providerParams: {
    fields: '(id,firstName,lastName,email-address)'
}
```

Feel free to add more. See the fields you can addat  [https://developer.linkedin.com/docs/fields](https://developer.linkedin.com/docs/fields).

**Comment by rajeev37** [comment]
When I added this to linkedin strategy like:
server.auth.strategy(
            'linkedin',
            'bell',
            {   provider    : 'linkedin',
                password    : Config.linkedin.password,
                clientId    : Config.linkedin.clientId,
                clientSecret: Config.linkedin.clientSecret,
                providerParams: {
                     fields: '(id,firstName,lastName,email-address)'
               }
                scope       : Config.linkedin.scope,
                isSecure    : Config.linkedin.isSecure

            }
        );

Then, it throw an error:

151001/122854.078, [error], message: Failed obtaining linkedin user profile stack: Error: Failed obtaining linkedin user profile
    at Object.exports.create (/home/rajeev/projects/node/pinkhand-ui/node_modules/boom/lib/index.js:21:17)
    at Object.exports.internal (/home/rajeev/projects/node/pinkhand-ui/node_modules/boom/lib/index.js:262:92)
    at /home/rajeev/projects/node/pinkhand-ui/node_modules/bell/lib/oauth.js:274:43
    at /home/rajeev/projects/node/pinkhand-ui/node_modules/bell/node_modules/wreck/lib/index.js:472:20
    at finish (/home/rajeev/projects/node/pinkhand-ui/node_modules/bell/node_modules/wreck/lib/index.js:301:20)
    at wrapped (/home/rajeev/projects/node/pinkhand-ui/node_modules/hoek/lib/index.js:858:20)
    at onReaderFinish (/home/rajeev/projects/node/pinkhand-ui/node_modules/bell/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
    at endWritable (_stream_writable.js:478:3)
    at Writable.end (_stream_writable.js:443:5)
    at IncomingMessage.onend (_stream_readable.js:490:10)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)


Am I doing something wrong?

**Comment by PaulMougel** [comment]
Try using `(id,first-name,last-name,email-address)`.

**Comment by rajeev37** [comment]
@PaulMougel  still getting same error.

**Comment by PaulMougel** [comment]
Looks like I forgot a `:` before the left parenthesis. Here is my current exact configuration:

```js
server.auth.strategy('linkedin', 'bell', {
  ...,
  providerParams: {
    fields: ':(' + linkedin.BASIC_PROFILE_FIELDS.join(',') + ')'
  }
});
```

linkedin.js
```
module.exports.BASIC_PROFILE_FIELDS = [
  'id',
  'first-name',
  'last-name',
  'maiden-name',
  'formatted-name',
  'phonetic-first-name',
  'phonetic-last-name',
  'formatted-phonetic-name',
  'headline',
  'location',
  'industry',
  'current-share',
  'num-connections',
  'num-connections-capped',
  'summary',
  'specialties',
  'positions',
  'picture-url',
  'picture-urls::(original)',
  'site-standard-profile-request',
  'api-standard-profile-request',
  'public-profile-url',
  'email-address',
];
```

And I'm getting back the email address in `request.auth.credentials.profile.raw.emailAddress`.

**Comment by ldesplat** [comment]
I would appreciate a PR for `Providers.md` documenting the `providerParams: fields` and how it should be formatted. The LinkedIn provider should have done that formatting in the first place to be in line with the others but we can document it for now.

**Comment by rajeev37** [comment]
@PaulMougel Its working now .Thanks for your valuable help and thanks @ldesplat for such a great module.

**Comment by PaulMougel** [comment]
I'm glad I could help.
Good suggestion @ldesplat ; I'll work on a quick PR over the week-end.
