### ISSUE TITLE
No 'Access-Control-Allow-Origin' header issue

### ISSUE THREAD

**Issue by gragra100** [hapijs/bell#149]
Hi, i know that there are a lot of this issues, but they are all closed.
i am in a similar situation: https://github.com/hapijs/bell/issues/123
i have the same error 
> XMLHttpRequest cannot load https://www.facebook.com/v2.3/dialog/oauth?client_id=1304261&respo…k&state=Cq5NQRkW8TuvW0HDuZz2zo&scope=public_profile%2Cuser_friends%2Cemail. 
 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

i am using bell and this is the strategy: 
>server.auth.strategy('facebook', 'bell', {
    provider: 'facebook',
    password: 'password',
    clientId: process.env.FB_CLIENTID,
    clientSecret: process.env.FB_CLIENTSECRET,
    isSecure: false,
    scope: ['public_profile', 'user_friends', 'email'],
    profileParams: {
      fields: 'id,email,first_name,gender,last_name,link,locale,name,timezone,updated_time'
    },
  });

>server.route({
    method: ['GET', 'POST'],
    path: '/auth/facebook',
    config: {
      auth: 'facebook',
      handler: internals.login
    }
  });

In the front-end with angular.js to log-in i use this:
>function Redirect($state, $window) {
    return {
      redirectToAuth: function() {
        // redirect the user to the server for auth
        $window.location.href = "http://" + $window.location.host + "/auth/facebook";
      }
    };
  }

**Comment by ldesplat** [comment]
You're redirecting the user way out of the angular application so if you just do
`window.location.href = "http://" + $window.location.host + "/auth/facebook";` it may work?
Notice the missing `$` on the first window. Who knows what angular tries to do :)

If you still have problems you can do `window.open("http://" + $window.location.host + "/auth/facebook");` that one has to work! I know it opens a pop-up window.

I know I've done it in the past without doing any of that but I don't have access to that source code anymore.

**Comment by gragra100** [comment]
Thank you but it doesn't work... If i use window.location.href = "http://" + $window.location.host + "/auth/facebook"; without $ it gave me the same 'Access-Control-Allow-Origin' header error.
 If i try with window.open it give me this: Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=app&p1=Error%3A%20%…2F%2Flocalhost%3A8080%2Fpublic%2Flib%2Fangular%2Fangular.min.js%3A19%3A339)

what can i do? Are you sure that the problem is in angular? can i add an header with 'Access-Control-Allow-Origin' in the bell strategy?

**Comment by ldesplat** [comment]
I know I wasn't any help there! Were you able to figure it out? Have you tried with Hapi 11 since it has CORS updates? (note, that I haven't run tests with bell against Hapi 11 yet).

**Comment by ldesplat** [comment]
closing the issue due to inactivity.
