### ISSUE TITLE
Bell does not work with Hapi 10

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/bell#151]
Hi,

Just tried the example from the front page of the documentation.
The, from the "examples" folder.
```javascript
// Load modules

var Hapi = require('hapi');
var Bell = require('bell');


var server = new Hapi.Server();
server.connection({ port: 8000 });

server.register(Bell, function (err) {

    server.auth.strategy('twitter', 'bell', {
        provider: 'twitter',
        password: 'password',
        isSecure: false,
        // Make sure to set a "Callback URL" and
        // check the "Allow this application to be used to Sign in with Twitter"
        // on the "Settings" tab in your Twitter application
        clientId: 'xxx',                               // Set client id
        clientSecret: 'yyy'                            // Set client secret
    });

    server.route({
        method: '*',
        path: '/bell/door',
        config: {
            auth: 'twitter',
            handler: function (request, reply) {

                reply('<pre>' + JSON.stringify(request.auth.credentials, null, 4) + '</pre>');
            }
        }
    });

    server.start(function (err) {

        console.log('Server started at:', server.info.uri);
    });
});

```

And here is what I have in the console when starting the server:
![image](https://cloud.githubusercontent.com/assets/839290/10263101/58e439de-69e1-11e5-9528-66122c38bf4f.png)

Are the examples outdated?

Regards,

**Comment by PaulMougel** [comment]
It looks like bell does not work yet with `hapi@10.x`. Try with `hapi@9.x`, and the example should work just fine.

**Comment by PavelPolyakov** [comment]
@PaulMougel 
Thanks, waiting for the plugin update then.

**Comment by ldesplat** [comment]
Looks like Hapi 10.0.x works, but it definitely broke with 10.1.x in a very bad manner and breaks in a much better manner with Hapi 10.2.x.

Either bell is registering itself in a way that was never supported (most likely) or Hapi just broke semver :)

**Comment by ldesplat** [comment]
I have identified 2 issues and already raised one with Hapi. I am still tracking down the other one which is a bit more serious. Definitely do not use it with Hapi 10 for now. Also, I have taken down the liberty to change the title of this issue.

**Comment by hansman** [comment]
I got the same problem.

**Comment by ldesplat** [comment]
Once Hapi 9.4.0 is released, then Bell will work. Eran fixed up the main issue very fast :). Bell's tests currently fail with Hapi's master branch but that's partially Bell's fault and has no repercussions on Bell's behavior. With the tests fixed, then Bell's tests all pass

**Comment by ldesplat** [comment]
Well, Hapi 10.4.0 fixes the two issues. So Bell tests now pass with Hapi 10.4.0. We are missing 1 line of coverage because Hapi 10 does the right thing unlike Hapi 9 but apart from that it's good.

**Comment by PavelPolyakov** [comment]
@ldesplat 
Thanks for the updates!
