### ISSUE TITLE
Run tests against Hapi 9 and 10

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#152]
Since, we all want to use Hapi 10 as shown in #151!

**Comment by arb** [comment]
I'm very curious how you're going to do that.

**Comment by devinivy** [comment]
It wasn't pretty, but I did this in the past: https://github.com/devinivy/dogwater/blob/6b8db9a6dd5aa0cdd18d550d6931fe5aa6fcab67/test/index.js

Might want to check out https://github.com/npm/npm/issues/5499
