### ISSUE TITLE
Google provider isn't passing providerParams properly

### ISSUE THREAD

**Issue by ericeslinger** [hapijs/bell#156]
Specifically, I need access_type: 'offline' and approval_prompt: 'force' to go through. This worked in bell 3, but stopped working in bell 5. I'm not sure if google's oauth2/v2 endpoint expects a differently-formatted request, but if I change the auth parameter in google.js from https://accounts.google.com/o/oauth2/v2/auth to https://accounts.google.com/o/oauth2/auth, everything works just fine.

If only I could figure out how to google for google documentation - I haven't yet found a nice, authoritative "this is the difference between oauth2 and oauth2/v2" document anywhere.

**Comment by hems** [comment]
i'm having some issues with not receiving displayName and first / last name from some users when they logging in as well.

i still didn't figure it out as well.

**Comment by ericeslinger** [comment]
Turns out the providerParams is just fine. The problem is that `approval_prompt=force` was changed to `prompt=consent` in the new v2 endpoint, per [this SO post](http://stackoverflow.com/questions/33137140/googles-oauth2-endpoint-v1-vs-v2-changes/33156346#33156346). Which, of course isn't documented or anything, but who expects google to document their changes. 

Closing this, since it's not a bell bug, at most it's a documentation bug for bell.
