### ISSUE TITLE
google credentials with empty displayName and name ?

### ISSUE THREAD

**Issue by hems** [hapijs/bell#157]
I just noticed some users are having problems with empty DisplayName and name when logging in with google.

On their gmail their info is correct, but i suspect they never entered on google+ and that is were the problem lives?

[This stackoverflow answer](http://stackoverflow.com/questions/28382282/getting-blank-name-display-name-from-google-plus-api?answertab=votes#tab-top) says something about using plus.login scope, but i'm not exactly sure how to test this on bell.

Any ideas?

````
{ provider: 'google',
 token: 'ya29[...]',
 refreshToken: undefined,
 expiresIn: 3599,
 query: {},
 profile:
  { id: '[...]',
    username: undefined,
    ** displayName: '', **
    ** name: { first: '', last: '' }, **
    email: '[...]',
    raw:
     { id: '[...]',
       email: '[...]',
       verified_email: true,
       name: '',
       given_name: '',
       family_name: '',
       picture: 'https://lh4.[...].jpg',
       hd: '[...]' } } }
````

**Comment by ericeslinger** [comment]
Did you add `https://www.googleapis.com/auth/plus.login` as a scope in your bell definitions?

**Comment by hems** [comment]
@ericeslinger i didn't! 

what this is supposed to do differently?

where could i find more documentation about it?

the confusing thing is : i already have about 150 registered users and some of them are totally fine and some of them had this issue, so i'm wondering if changing the scope could potentially change the way my application would have to work in order to parse information from the old and new users at the same time..

any more information is more than appreciated!

**Comment by ldesplat** [comment]
See hapijs/bell#108 for some information. If that does not help you, maybe you can @ mention the person who made those changes and see if he has any ideas.

**Comment by hems** [comment]
@ldesplat i just added:
````
            scope: [
              'profile'
            ]
````

and so far i didn't see any difference, will let you know once i test it properly.
