### ISSUE TITLE
Twitter OAuth: Failed obtaining twitter temporary credentials

### ISSUE THREAD

**Issue by tanepiper** [hapijs/bell#161]
Hi there,

I've been trying to implement a login with Twitter for an app I'm working on.  Following the example provided I get the following stacktrace:

```
Debug: auth, unauthenticated, error, twitter
    Error: Failed obtaining twitter temporary credentials
    at D:\Documents\GitHub\myapp\node_modules\bell\lib\oauth.js:397:34
    at D:\Documents\GitHub\myapp\node_modules\bell\node_modules\wreck\lib\index.js:472:20
    at finish (D:\Documents\GitHub\myapp\node_modules\bell\node_modules\wreck\lib\index.js:301:20)
    at wrapped (D:\Documents\GitHub\myapp\node_modules\bell\node_modules\hoek\lib\index.js:866:20)
    at [object Object].onReaderFinish (D:\Documents\GitHub\myapp\node_modules\bell\node_modules\wreck\lib\index.js:363:16)
    at [object Object].g (events.js:260:16)
    at emitNone (events.js:72:20)
    at [object Object].emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
    at endWritable (_stream_writable.js:478:3)
```

I've taken the headers passed to the URL and used Postman, I'm also getting this from twitter (but because OAuth not sure if this is also correct)

```
{
  "errors": [
    {
      "code": 32,
      "message": "Could not authenticate you."
    }
  ]
}
```

I've tried to dig in a bit further and it does seem like I'm getting a 401 back, it seems when the options inside `internals.Client.prototype._request` are `{ desc: 'temporary credentials' }`.

I've double and triple checked my clientId and clientSecret are correct too.

**Comment by tanepiper** [comment]
Scratch that - turns out Twitter had not saved my callback url in the app - so this locks it into OOB mode.  Once I did that, started doing the oauth dance.  However has lead to another issue:

```
Debug: auth, unauthenticated, error, twitter
    Error: Missing twitter request token cookie
    at Object.authenticate (D:\Documents\GitHub\myapp\node_modules\bell\lib\oauth.js:80:31)
```

Digging into this one too, it seems that `request.state` is an empty object, `cookie` is set to `bell-twitter`

**Comment by tanepiper** [comment]
OK! More digging about, ended up going into the Hapi internals to find that if you are developing locally without https, you MUST set `isSecure: false` when making a OAuth login request to Twitter.

**Comment by damusix** [comment]
Just went through the same chain of errors LOL! Thank you tanepiper!
