### ISSUE TITLE
Simulated mode

### ISSUE THREAD

**Issue by hueniverse** [hapijs/bell#167]

**Comment by DJMcK** [comment]
@ldesplat noticed this hasn't landed in a published release yet. Do you mind publishing a new version if all is good? Much appreciated.

/cc @hueniverse

**Comment by ldesplat** [comment]
I am sorry but I won't be able to until this weekend. I am in the middle of a big move right now. Maybe @geek can help if he's feeling generous and you really need it :)

**Comment by DJMcK** [comment]
Not a problem @ldesplat! I'm in no critical need for the feature. This feature is just a real nice-to-have that'll simplify things and let me remove some code (which is always nice!)

**Comment by ldesplat** [comment]
@DJMcK 6.1.0 is released.

**Comment by DJMcK** [comment]
@ldesplat Awesome, thank you.
