### ISSUE TITLE
Facebook isSecure bug? 

### ISSUE THREAD

**Issue by ddaza** [hapijs/bell#170]
I have 2 configs set up in my server. (Facebook and Google) for `bell@6.0.x`

I have an SSL secured server and I have set `isSecured='true'` in both configs.
  
```javascript
        server.auth.strategy('facebook', 'bell', {
            provider: 'facebook',
            password: 'password', 
            clientId: server.settings.app.facebookClientId,
            clientSecret: server.settings.app.facebookClientSecret,
            profileParams: {
                fields: ['email']
            },
            isSecure: true
        });

        server.auth.strategy('google', 'bell', {
            provider: 'google',
            password: 'mypassword',
            clientId: server.settings.app.gcloudClientId,
            clientSecret: server.settings.app.gcloudClientSecret,
            location: 'https://thisismyserver.com',
            isSecure: true
        });
```

When tested locally ( only changing `isSecure='false'`) everything seems to work properly.

But when deployed to my server the config fails and responds with: 
`Invalid setting  - isSecure must be set to false for non-https server`

This only happening with the **Facebook** config but not with the **Google** one.

**Comment by ldesplat** [comment]
How come you don't have the location field for facebook? You most likely need to configure that as well just the same way you did with google.

**Comment by ddaza** [comment]
I think that's the issue. Thanks.
