### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by gordysc** [hapijs/bell#171]
I'm trying to use CORS in hapijs 11.1.2 with this library (bell), but I can't seem to get the 'Access-Control-Allow-Origin' header to be specified.  I've seen quite a few similar examples (#149, #123, #74), but haven't had any luck.  I'm making an AJAX call from the front end to hit this route to authenticate with Facebook and then do some additional logic.  However, whenever I hit this route I'm not seeing the 'Access-Control-Allow-Origin' in the response.  Do I have to do anything to Bell to enable CORS?

```
'use strict';

exports.register = function(server, options, next) {
  server.route({
    method: 'GET',
    path: '/oauth/facebook',
    config: {
      auth: 'facebook',
      tags: ['api'],
      cors: true,
      handler: function (request, reply) {
        if (request.auth.isAuthenticated) {
          // do some logic here
          return reply.code(204);
        }
        return reply.code(401);
      }
    }
  });
  return next();
};

exports.register.attributes = {
  name: 'oauth-facebook-' + process.env.npm_package_name,
  version: process.env.npm_package_version
};
```

**Comment by gordysc** [comment]
Handled this via UI library

**Comment by DamodarSojka** [comment]
I am having same problem. Would it be possible to specify what 'UI library' means? Thanks in advance.
