### ISSUE TITLE
Configurable 'state' value for GitHub

### ISSUE THREAD

**Issue by hazkiel** [hapijs/bell#172]
Hi, I'm currently using the Github provider and I need to link the user's Github account with his local one.
The issue is that I don't have a way to track which user is going through the GitHub OAuth process

If I had access to the 'state' variable being sent internally by bell to the Github /authorize API, I could save that in the local user account and be able to link the Github profile later by loading the user using the returned 'state' value.

Instead of this, I'm currently forced to use a cookie to keep track of the user Id.
Is there any reason why the 'state' variable is not accessible before being sent to Github?

**Comment by ldesplat** [comment]
I am so sorry, I completely forgot to reply to this issue.

I do not understand how you would track the user even if we gave you access to the state. How would that API work... we generate the state on the first request, how do you know it's coming from the same user you were tracking before (somehow without a cookie?)?

**Comment by hazkiel** [comment]
Well, Github for instance returns the same state parameter you provide in
its response, so I would do this:
1. save the state value in the user's db record on the first request
2. bell calls the Github API
3. Github redirects to our own API and provides the same state value
4. use this value to find the user record

I hope this explains what I'm aiming for.

**Comment by ldesplat** [comment]
Ok, I understand what you're trying to do. I believe most people are already tracking their users through some sort of session mechanism so it's not very useful except in special cases like yours.

You are free to submit a PR that does something like that. You would have to make sure that the generation of the state variable is not only properly random but also guarantees uniqueness. If I were to consider a PR like that, I would highly prefer the generation of the state to be done outside of Bell. I prefer Bell to be secure by default, so I would offset the secure generation of state to the client code which may have better ways to ensure that uniqueness.

**Comment by ldesplat** [comment]
BTW, the way we currently generate should be damn quite unique but it's not guaranteed. Also, the question is how do we give you access to the nonce.. I have no idea how to pass that as an API.
Which is really why I think the only way is to make the user application then generate the nonce. But, to be very frank I really don't like it. I don't want people to screw that part.

**Comment by hazkiel** [comment]
Actually, I added some logic to store a cookie with the userId when the first request comes in and I'm reading that back when the user is redirected back from Github so it's working out fine.
I basically copied your logic for the 'bell-provider' cookie that stores the state, figured out I might do the same as well since we can't avoid that cookie either.
I think that we can close this ticket if you have nothing else to add. Thanks.
