### ISSUE TITLE
custom provider

### ISSUE THREAD

**Issue by MarceloEmmerich** [hapijs/bell#180]
Hi Guys, how can I add a custom provider at runtime? I would like to use our own OAuth2 server.

**Comment by ldesplat** [comment]
Do you really need to add it at runtime?

All the documentation is here: https://github.com/hapijs/bell/blob/master/API.md
And just take a look at existing implementation in lib/providers

Maybe you can explain why you want custom providers at runtime?

**Comment by MarceloEmmerich** [comment]
well, maybe it is possible differently, what I need is to use our custom OAuth2 server. So how can I pass it's specific endpoints to bell?

**Comment by ldesplat** [comment]
You create your own provider. You have the API docs that tell you how to do that along with lots of examples in `lib/providers`
