### ISSUE TITLE
Bell is not installing with hapi12.xx.xx or higher version 

### ISSUE THREAD

**Issue by itzatul** [hapijs/bell#192]
npm WARN peerDependencies The peer dependency hapi@13.x.x included from bell will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bell"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package hapi@12.1.0 does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:

**Comment by devinivy** [comment]
Bell v7 supports just hapi v13 as a peer.  See the release notes here: https://github.com/hapijs/bell/issues/189.  I'd suggest upgrading hapi or downgrading bell.

**Comment by itzatul** [comment]
Hapi 13v its working fine, Thanks
