### ISSUE TITLE
Support for Slack Oauth team domain?

### ISSUE THREAD

**Issue by mutaphore** [hapijs/bell#200]
Is there a way to specify what team the Slack Oauth flow brings to?

**Comment by ldesplat** [comment]
@declandewet contributed the plugin, maybe they can answer?

**Comment by declandewet** [comment]
Yep, just use `providerParams` to pass that info to Slack directly:

```js
server.auth.strategy('slack', 'bell', {
  provider: 'slack',
  providerParams: {
    team: 'T02XXXXXX' // slack team ID
  },
  password: 'your slack api password',
  clientId: 'your slack client id',
  clientSecret: 'your slack client secret'
})
```

You can find your team ID here: https://api.slack.com/methods/auth.test/test

**Comment by mutaphore** [comment]
Thanks for the fast response!
