### ISSUE TITLE
wordpress provider

### ISSUE THREAD

**Issue by pankajpatel** [hapijs/bell#203]
Hello,

I needed the wordpress provider for my project, so I have created one at [https://github.com/pankajpatel/bell](https://github.com/pankajpatel/bell).

Can anyone please review it.

**Comment by ldesplat** [comment]
Looks good to me at first glance. Feel free to submit the PR :)
Thank you!

**Comment by pankajpatel** [comment]
Do I need to add the documentation bit for this provider?

**Comment by ldesplat** [comment]
Closed by #204
