### ISSUE TITLE
Twitter: another method call instead of "users/show" / configuration

### ISSUE THREAD

**Issue by tameraydin** [hapijs/bell#211]
Hi, the application I am working on tries to setup an account through the e-mail I get via social auth. 

Currently, Twitter provider makes a call ``https://api.twitter.com/1.1/users/show.json`` and this method provides some user information but not the email. Instead I would prefer to call ``account/verify_credentials`` where I can get the infromation I need.

I took a look also to other providers in Bell, and some of the methods supports extra config fields. 
Would it be possible to do the same for determining the API url/method to be called -by somehow exposing a config prop to the provider interface-?

I can work on a PR if you agree with the above.. What are your thoughts on this case?

**Comment by ldesplat** [comment]
If you think it should be part of the default provider go ahead and change it.

For providing configuration to change an existing provider, that does not sound too bad but then just taking an existing provider and customizing it exactly for your needs on a project is not an obscene thought either.

Either way, contributions are definitely welcome :)

**Comment by tameraydin** [comment]
Hi @ldesplat, I created a PR ( #221 ).. Let me know if you have any remarks.
