### ISSUE TITLE
Logout from any of OAuth?

### ISSUE THREAD

**Issue by panKt** [hapijs/bell#212]
Let's say user logged into my system using bell+twitter. Is it possible to say bell to log out a a person from system without logging out from twitter?

**Comment by ldesplat** [comment]
Bell just allows you to grab a token and some information from the providers. The way you implement session management is up to you. You should look into hapi-auth-cookie or a similar plugin that handles this for you.

So, you can use Bell in such a way that the 3rd party provider tells you, yes this specific user is authorized to access out service and here's a token to interact with our service on behalf of that user. As you can see Bell does not deal with login or logout per say. Most of us, use it as a way to implement login on our own websites but you still need to manage the session yourself.

Cheers!
