### ISSUE TITLE
Bitbucket authentication does not work

### ISSUE THREAD

**Issue by jskang** [hapijs/bell#220]
Hi

I've been trying to use Bell for Bitbucket authentication but cannot get it to work. For bitbucket I continuously get Internal 500 error. I have tried it with the examples that was provided http://mph-web.de/social-signup-with-twitter-using-hapi-js/. I confirmed that it works for twitter and github but not bitbucket.

Thanks,

**Comment by ldesplat** [comment]
If you can figure out why it's not good. Please submit a PR. Maybe your configuration was wrong?

**Comment by Belar** [comment]
Just tested BitBucket authentication, no problems. If you could show us your config or error details from debug, it would be easier to help.

**Comment by jskang** [comment]
I finally got it to work. For some reason error message didn't show up. After digging in, I found out that it was doing the oauth properly but was not able to get the user information. So I started looking at my settings and it turns out that by default bitbucket does not share read and write on user credentials. I check off email and read access and it started working. Thanks!
