### ISSUE TITLE
Use API V2 for Dropbox provider

### ISSUE THREAD

**Issue by klaronix** [hapijs/bell#241]
API V1 is now deprecated [https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/). V2 uses new urls (simple) but needs POST request for getting user info [https://www.dropbox.com/developers/documentation/http/documentation#users-get_account](https://www.dropbox.com/developers/documentation/http/documentation#users-get_account). Is someone already working on this?

**Comment by ldesplat** [comment]
We would gladly accept a PR!

There are a lot of providers, so we depend on the community at large to keep them updated.
