### ISSUE TITLE
How to integrate with the frontend?

### ISSUE THREAD

**Issue by DamodarSojka** [hapijs/bell#245]
I am having hard time understand how bell authentication flow should work with the frontend, I am using angular but this is not an angular specific question. 

Should call to the bell endpoint be made from the new tab 
`$window.open(API_URL + "/linkedin/auth")`
which allows backend to retrieve data from the provider but then the tab that the user initiated 3rd party login from is still at the login page, so frontend is not aware of the authentication flow anymore.

Or call the bell endpoint using
`$http.get(API_URL + "/linkedin/auth")`
which triggers CORS issue (using Chrome) regardless of using cors: true on the route:
XMLHttpRequest cannot load https://www.linkedin.com/uas/oauth2/authorization?... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

I would be grateful for any help. 
I have already inspected other CORS related issues I have found for bell, they haven't been helpful.

**Comment by garthk** [comment]
I'm using something similar to the following:

```js
    server.auth.strategy('session', 'cookie', 'required', {
        appendNext: true,
        clearInvalid: true,
        cookie: SESSION_COOKIE_NAME,
        isSecure,
        password: process.env.COOKIE_PASSWORD,
        redirectOnTry: false,
        redirectTo: '/login',
    });

    server.auth.strategy('auth0', 'bell', {
        provider: auth0Provider,
        config: { domain: process.env.AUTH0_DOMAIN },
        password: process.env.COOKIE_PASSWORD,
        clientId: process.env.AUTH0_CLIENT_ID,
        clientSecret: process.env.AUTH0_CLIENT_SECRET,
        isSecure: true,
        isHttpOnly: true,
        location: process.env.HAPI_URI,
        scope: ['openid']
    });

    server.route({
        method: 'GET',
        path: '/login',
        config: {
            auth: {
                strategies: ['auth0'],
                mode: 'required'
            }
        },
        handler: function (request, reply) {
            request.cookieSet({ request.auth.credentials });
            reply.redirect('/');
        },
    });
```

By default, all routes will require the `session` strategy. If the cookie is missing, it'll redirect to `/login`. The handler won't get called until `bell` is finished, at which time you'll set the session cookie and redirect back. Your page will then get reloaded. If you pass cookies with your back end requests, it'll all Just Work from then on.

That leaves you with two corners: people hitting you for the first time, and the cookie expiring.

For the first time: if the static route serving the index has the default strategy, your JavaScript will have the cookie by the time it's loaded. If not, ensure your JavaScript can also be fetched without authentication. That'll leave you without a cookie as if it had expired.

For expired cookies, you need to sense the redirection from your API routes to authenticate. For `XMLHttpRequest`: check `responseURL` to catch redirects to your provider's login page and set `window.location` to follow. For `fetch`:  set the options `credentials: 'same-origin'` for the cookies and `redirect: 'manual'`, catch 302 yourself, and follow. 

By the time you're reloaded after authentication, you'll have a cookie and the next XHR/fetch will work fine as above.

Let me know how you go! If anyone else has corrections or simpler approaches, please do wade in.

**Comment by grenager** [comment]
It would be super helpful to provide some examples of how to use this with a front-end. I'd like to use bell to provide authentication on my back-end API, but of course the third-party oauth providers typically want to show a page to the user and get them to click. It's not clear how to embed that workflow into a front-end app. I'm guessing I need to configure the back-end to return some kind of redirect, and then run a page refresh through the back-end redirect, or something like that. Any thoughts?

**Comment by pabx06** [comment]
yup same question here the backend for twitter show up a nice form to be filled by user:  login and password ...

my front end is angular2 2 year agao i was  with angular 1 i was able to use express back end to intercept  and use virtual router template served by passportjs/backend.

but now my workflow is completly different.

now i am wondering if i can use templateURL of angular2 component

**Comment by flipxfx** [comment]
We are having this issue also, we would love the ability to customize what happens when the user is unauthenticated or have a flag built in. Currently without bell we use an `'X-Requested-With': 'ajax'` header to identify the call is being made from an API call and instead of redirecting we return a 401.

**Comment by captainjackrana** [comment]
Its a little old, but anyone still having confusions about this should see this flow ( example uses Express + passport.js but you can get the idea)
https://github.com/mean-expert-official/loopback-sdk-builder/wiki/7.-Social-Passport-Integration
