### ISSUE TITLE
Changelog for major versions

### ISSUE THREAD

**Issue by bbatliner** [hapijs/bell#246]
Bell has been super active lately, it seems like, and I can't keep up with the breaking changes. Is there a version history or changelog?

**Comment by ldesplat** [comment]
You can see the Milestones for what changed: https://github.com/hapijs/bell/milestones?state=closed
We also have release notes for every major version to denote what broke and that can be seen here: https://github.com/hapijs/bell/issues?q=label%3A%22release+notes%22+is%3Aclosed

This is true across all the hapijs projects.
