### ISSUE TITLE
how to handle error when facebook user refuses to give authorization, please guide. 

### ISSUE THREAD

**Issue by hbarve1** [hapijs/bell#257]

**Comment by ldesplat** [comment]
I think that's a very worthwhile endeavor to show a bit more of the real-life usage.

**Comment by ldesplat** [comment]
We have a section of the documentation that talks a bit about it: https://github.com/hapijs/bell/blob/master/API.md#handling-errors

Unfortunately, it will be different for different providers. I am working on some enhancements that will demonstrate this exact thing and more with a subset of the supported providers.

Until then, if somebody wants to add documentation for the specific providers they are welcome to. You will notice in the Providers documentation, we link straight to their documentation as well.
