### ISSUE TITLE
Failed obtaining access token 

### ISSUE THREAD

**Issue by parimal-padture** [hapijs/bell#258]
I have configured strategy as follows , request for authorization code gets completed , but when post request for access token gets fired it returns "Failed obtaining access token ", i have also tried to run request from postman and it returns me the access token , i don't know what i am missing in strategy configuration. i have also tried using bell-oidc but no luck, it will be great if i can get some reference/working example  to azure ad third party login using bell.

`server.auth.strategy('azuread', 'bell', {
        provider: {
            protocol: 'oauth2',
            useParamsAuth: true,
            auth: config.authUrl,
            token: config.tokenUrl
        },
        isSecure: false,
        clientId: config.clientID,
        clientSecret: config.clientSecret,
        password: config.password,
        location: config.callbackURL,
        skipProfile: true,
        providerParams: {
            response_mode: "query"
        },
        allowRuntimeProviderParams: true
    });`

**Comment by ldesplat** [comment]
You should check out https://github.com/hapijs/bell/pull/185

I never merged that PR though I think it was quite worthwile, I wanted some sort of way to more completely support it, but this should help you get it working if I am correct that azuread is really microsoftonline.com

**Comment by ldesplat** [comment]
Closing issue, but feel free to re-open if you want to give more details.
