### ISSUE TITLE
Support for reading id_token from an OpenId Connect flow

### ISSUE THREAD

**Issue by wennergr** [hapijs/bell#261]
Hey.

[OpenId Connect](http://openid.net/connect/) starts out as an oAuth2 flow and bell can therefor be reused for the initial phase. (authentication code flow)

One difference is that OpenID connect can exposes two tokens, one access token but also an id token. It would be fantastic if there was a way to read this id token.

I'm not suggesting to add full OpenID Connect support but I would be able to use the bell library if the payload from the token endpoint was exposed, for example, as an artifact.

More then happy to put together a PR if this sounds fair / reasonable.

**Comment by ldesplat** [comment]
That sounds fair to me. It could be exposed here https://github.com/hapijs/bell/blob/master/lib/oauth.js#L103 such that you can access it using `request.auth.credentials` and continue on with the flow. Are you sure this will work though? I have been out of that world for more than a year and I don't fully remember but OpenID Connect implementations tend to be picky.

**Comment by wennergr** [comment]
Tested it with our OIDC provider with the following change on `https://github.com/hapijs/bell/blob/master/lib/oauth.js#L103`

```

**Comment by wennergr** [comment]
Tested it with our OIDC provider and the following change:

```
diff --git a/lib/oauth.js b/lib/oauth.js
index a55a5c2..4622874 100755
--- a/lib/oauth.js
+++ b/lib/oauth.js
@@ -254,6 +254,7 @@ exports.v2 = function (settings) {

             const credentials = {
                 provider: name,
+                idToken: payload.id_token,
                 token: payload.access_token,
                 refreshToken: payload.refresh_token,
                 expiresIn: payload.expires_in,
```

And it worked.

**Comment by wennergr** [comment]
I will put together a PR.

**Comment by garthk** [comment]
I just ran into this, also. Passing `payload` back as the [optional authentication artifacts](http://hapijs.com/api#serverauthschemename-scheme) would do the trick, i.e.:

```
return reply.continue({ credentials, artifacts: payload });
```

… given any but the standardised properties are provider-specific.

Hacky workaround: copy your favourite provider file; replace `provider` with a function that shoves its second argument into the `credentials` object somewhere.
