### ISSUE TITLE
Not getting email from twitter

### ISSUE THREAD

**Issue by rajeev37** [hapijs/bell#268]
Is it possible to get email address from twitter using bell plugin?
I am using this strategy.

      `server.auth.strategy( 'twitter',  'bell',
         {   provider: "twitter",
            password: "&GGHK@$EGsed&*565^*&sdfsdfsdfsdsgfgghfghfghHJHJjgjkkj",
            clientId: "cliendID**",
            clientSecret: "secretID***",
            isSecure: false,
            scope: ['public_profile', 'email']

            }
        );`

It fetch some detail but not email address. How can I fetch email address also?

**Comment by ldesplat** [comment]
See the twitter documentation: https://dev.twitter.com/rest/reference/get/account/verify_credentials

They have to whitelist you first.
