### ISSUE TITLE
question: oauth2 flow

### ISSUE THREAD

**Issue by aphuang2013** [hapijs/bell#271]
I'm trying to understand the oauth2 v2 flow.  if the skipProfile call is set, then what is the next step?   I know the credentials get returned but the settings.provider.profile.call(settings, credentials, payload, get, () =>... requires "get" to be called, but if there is no "userinfo" uri, what will be the correct response here?

**Comment by ldesplat** [comment]
Nothing gets done. You get your credentials and no other calls are made. https://github.com/hapijs/bell/blob/master/lib/oauth.js#L111

See how we `return reply.continue()` thus returning from the function and telling Hapi we're done.
