### ISSUE TITLE
add the request to the profile function

### ISSUE THREAD

**Issue by TinOo512** [hapijs/bell#274]
Hi, 

I have several routes which are using the same facebook strategy. I would like to personnalise the profile and the fields requested to facebook depending of the route. I'm thinking to add the request to the profile function like so : 

_ROUTE:_

``` js
server.route({
  ...
  config: { app: { fb: { profile: 'user', fields: ['id', 'name', 'email'] } } }
});
```

_PROFILE:_

``` js
function (request, credentials, params, get, callback) {
  const { fb } = request.route.settings.app;
  ...
}
```

Let me know what do you think ? I'll do the PR if it sound raisonnable for you :smile:

**Comment by ldesplat** [comment]
So this may not cover everything but there is this already https://github.com/hapijs/bell/blob/master/API.md#customized-scope-and-params

Do you need anything more?

**Comment by TinOo512** [comment]
@ldesplat yes, basically I would like to pass a function to `profileParams`. Regarding the code I thought it would be easier to just add the `request` to this existing function.

**Comment by TinOo512** [comment]
@ldesplat Do you see the use case ? Does it sound reasonable to merge if I open a PR ?

**Comment by hueniverse** [comment]
I see what you are asking for, and I am not completely opposed but no one else has been asking for it. If there is more interest in passing the route config to the profile method, I'll consider exposing it.
