### ISSUE TITLE
Bitbucket Server

### ISSUE THREAD

**Issue by stjohnjohnson** [hapijs/bell#275]
So it looks like Stash was renamed into Bitbucket Server and only supports OAuth 1.  I'm happy to add support for it, but I'm uncertain as to where to add it.

Here are the two options I see:
Option 1 - Add params to the `bitbucket` provider to support a custom server with OAuth 1.
Option 2 - Add new provider called `bitbucket-server` with params for specifying server.

Params would be implemented similar to:
- https://github.com/hapijs/bell/blob/bcd53e58736e86502b0c58c7ed3229e761d4c4f8/lib/providers/github.js#L7-L8

What would you prefer?

**Comment by stjohnjohnson** [comment]
@ldesplat?

**Comment by ldesplat** [comment]
@stjohnjohnson If you are still interested. You may as well create a new provider since one is connecting to the publicly accessible bitbucket over oauth2 and the other would be over oauth1
