### ISSUE TITLE
Authorization with Facebook stopped working

### ISSUE THREAD

**Issue by sigod** [hapijs/bell#278]
This is what handler receives in `request.auth`:
```json
{
    "isAuthenticated": false,
    "strategy": "facebook",
    "mode": "try",
    "error": {
        "data": {
            "type": "Buffer",
            "data": ["(...lots of bytes here...)"]
        },
        "isBoom": true,
        "isServer": true,
        "output": {
            "statusCode": 500,
            "payload": {
                "statusCode": 500,
                "error": "Internal Server Error",
                "message": "An internal server error occurred"
            },
            "headers": {}
        }
    }
}
```

I'm unable to find source of the issue. I'm pretty sure it worked in the first days of August.

Tried with bell version 8.2.1 and 8.3.0. Also, tried to use different applications' credentials and different users. The same result in all cases.

Am I missing something? Or did Facebook change something?

Bell registration:
```js
Server.register(bell, (err) => {
	Server.auth.strategy('facebook', 'bell', {
		provider: 'facebook',
		password: Config.auth.cookie_password,
		clientId: Config.auth.facebook.id,
		clientSecret: Config.auth.facebook.secret,
		isSecure: !DevMode,
		location: Config.ownURL,
	})

	Server.route({
		method: ['GET', 'POST'],
		path: '/auth/facebook',
		config: {
			auth: {
				strategy: 'facebook',
				mode: 'try'
			},
			handler: app.facebook
		}
	})

	// ...
```

**Comment by ldesplat** [comment]
There must be some problem with your code? Or with the very latest version of Hapi...
https://bell.now.sh/  seems to work. I built it just for these issues :)
https://bell.now.sh/_src if you want to see the source code.
Looks like I last deployed it 57 days ago, so whatever version of Hapi was the most recent then is what it's working on.

**Comment by sigod** [comment]
I would be happy if it's just a problem with my code, but none of my code is invoked before server receives this error message.
Actually project uses Hapi v13.2.2. I tried to change it to v15.2.0 and test again. Few of dependencies haven't been met. But project seems to be working. I've got the same error message though.

> https://bell.now.sh/ seems to work

"This app is still in development mode ..."

**Comment by sigod** [comment]
OK, I found the root on this issue. It appears that Facebook changed requirements for applications. Now you're required to provide a set of valid OAuth redirect URLs for your application.
