### ISSUE TITLE
Strange issue with Hapi, Bell, and Node-config

### ISSUE THREAD

**Issue by tscrip** [hapijs/bell#279]
I am running into a strange error when using the node config module with bell. I am trying to pull in values from a config JSON file for server.auth.strategy. If I include them in my main file, it works correctly. If I pull them in from a JSON file, I get the error below. Anyone know why I would be getting this?

JSON segment looks like this:
```
"AuthenticationProviders": {
        "Facebook": {
                "provider": "facebook",
	        "password": "abc123",
		"clientId": "<REMOVED>",
	        "clientSecret": "<REMOVED>",
		"isSecure": false
		}
}
```

Here is the code that is throwing the error:
```
const Config = require('config');
var facebookAuth = Config.get('AuthenticationProviders.Facebook');

ValidationError: "util" is not allowed. "get" is not allowed. "has" is not allowed. "watch" is not allowed. "setModuleDefaults" is not allowed. "makeHidden" is not allowed. "makeImmutable" is not allowed. "getConfigSources" is not allowed. "_loadFileConfigs" is not allowed. "_parseFile" is not allowed. "_attachProtoDeep" is not allowed. "_cloneDeep" is not allowed. "_equalsDeep" is not allowed. "_diffDeep" is not allowed. "_extendDeep" is not allowed. "_stripYamlComments" is not allowed. "_stripComments" is not allowed. "_isObject" is not allowed. "_initParam" is not allowed. "_getCmdLineArg" is not allowed
```

My goal is to be able to specify the auth properties like this:
`server.auth.strategy('facebook', 'bell', facebookAuth);`

**Comment by jonathansamines** [comment]
@tscrip the reason is that `node-config` attaches the "config prototype" to each object in your properties in a recursive way.  That means that each subobject retrieved from your configuration file, results with the same properties as the root object.

See: https://github.com/lorenwest/node-config/blob/master/lib/config.js#L1067

**Comment by subins** [comment]
use server.auth.strategy('facebook', 'bell', Object.assign({}, facebookAuth));
