### ISSUE TITLE
Is bell for authentication only or can it be used for api consumption ?

### ISSUE THREAD

**Issue by mmc41** [hapijs/bell#282]
I am interested in using bell with hapijs to consume services from google, dropbox and the other services supported by bell. It is however unclear from the docs if bell only support authentication or if it provides the necessary tokens etc. so one can actually call into the various service API's? Could that be specified in the readme ?

**Comment by cvillerm** [comment]
Tokens issued during authentication are indeed available in the `request.credentials.auth` object:
* `token`: access token
* `refreshToken`: refresh token (if any)
* `expiresIn`: validity duration of access token

As these tokens are available only in the route handler secured by Bell, they need to be saved for later use (e.g. manage a session with a session cookie).
They can later be used to access a protected API (e.g. send the access token as Authorization Bearer HTTP header) or to communicate with the OAuth2 Authorization Server (e.g. to get a refreshed access token from the refresh token), but there is direct support (e.g. helper function) for this in Bell.
