### ISSUE TITLE
Remove or more comprehensively document provider.version

### ISSUE THREAD

**Issue by garthk** [hapijs/bell#288]
* Defined in the API documentation as "the OAuth version"
* Appears to be redundant given `provider.protocol`
* Validated as a `joi.string()`
* Doesn't appear to be used

**Comment by garthk** [comment]
(In case it helps, I'm working on TypeScript support for `bell`.)

**Comment by ldesplat** [comment]
Thanks, I'll take a look at depreciating this if it makes sense.
