### ISSUE TITLE
unable to retrieve facebook profile picture

### ISSUE THREAD

**Issue by ignivaravinderrikhi** [hapijs/bell#290]
Hi,

I am using basic configuration as shown in examples for fetching facebook profile data using **bell** and it is working flawlessly . But I am unable to retrieve the **_profile picture_** of the user which is my major requirement. Is there any solution/work around present for this situation .

Thanks

**Comment by ldesplat** [comment]
See http://stackoverflow.com/questions/11748941/facebook-oauth-no-picture-with-basic-permissions for some answers. You will need to specifically ask for it in the fields. Specifically `profileParams` https://github.com/hapijs/bell/blob/master/API.md#options
