### ISSUE TITLE
Support for OIDC and discovery urls

### ISSUE THREAD

**Issue by akiellor** [hapijs/bell#292]
I'm currently using bell for integrating with OIDC providers and recently found OIDC defines a spec for `discovery_endpoints` which simplify configuration.

I'm wondering if OIDC specifics would be considered part of the scope of `bell` or does it make sense to keep those specifics in another library.

**Comment by ldesplat** [comment]
I know I have placed interest in it and so many others. I think there's even open PRs for things like that. Ideally, I'd just want to support hooks to allow another library to handle all the specifics while allowing the basic oauth2 to work seamlessly underneath.

Unless someone wants to start maintaining Bell, expanding into proper support for OpenID Connect is quite an investment.

**Comment by sscarduzio** [comment]
@ldesplat what alternatives do you recommend if we need OpenID Connect for Hapi?
