### ISSUE TITLE
Document new Medium provider

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#293]
See https://github.com/hapijs/bell/commit/bd3702d2a37d7cdaf55ef0df2c838dc291d21bb2

**Comment by joshuacolvin** [comment]
I'm willing to help with this.

**Comment by AdriVanHoudt** [comment]
@joshuacolvin Take a look at https://github.com/hapijs/bell/blob/master/Providers.md for examples and feel free to open a PR!

**Comment by joshuacolvin** [comment]
I noticed that Bell's medium provider returns `token: https://medium.com/v1/tokens` and the medium documentation defines the endpoint as `https://api.medium.com/v1/tokens`. Which one should be referenced in Providers.md? Thanks.

**Comment by AdriVanHoudt** [comment]
The one bell uses. But are those interchangeable?

**Comment by joshuacolvin** [comment]
Not sure. Having trouble getting medium auth to work with either. Trying to decipher if it's something i'm doing wrong or related to [this](https://github.com/Medium/medium-api-docs/issues/62) issue.
