### ISSUE TITLE
Authorising with existing session

### ISSUE THREAD

**Issue by woutrbe** [hapijs/bell#296]
I know this plugin is mostly used for third-party authentication, but is there any support for authorising third-party accounts on top of existing session.

Here's my current scenario:
1.  User logs in through email/password form
2. User is given a JWT that must be provided on every request
3. User wants to authorise Twitter to their account

Step 3 is where I'm stuck at the moment,  how can I have a route with Twitter authentication, but also with JWT authentication.

I know routes can have multiple strategies, but this isn't what I'm looking for, I explicitly want to tell the route:
- User must have a valid JWT token
- Redirect user to Twitter OAuth page
- Redirect to callback endpoint with the same JWT

Is something like this possible?

**Comment by ldesplat** [comment]
In the past I've done this by doing my own auth strategy and explicitly calling the two strategies I want to combine since you can call their APIs directly. I can't find any samples off hand but hopefully somebody can point out an example somewhere.

**Comment by woutrbe** [comment]
@ldesplat That was my idea as well. I've sort of had the same issue when I was using Express + passport in the past, because the endpoints would involve:

`JWT -> Twitter -> OAuth screen -> Twitter -> JWT -> callback`

Which made it a bit difficult to manage, especially since you have to pass the JWT around, I'll give it a try.
