### ISSUE TITLE
Copy over the profile picture from Facebook?

### ISSUE THREAD

**Issue by grenager** [hapijs/bell#297]
Hi, it would be really helpful for me to get the profile picture from Facebook. Here's the required code change (I think):

```js
const query = {
                appsecret_proof: Crypto.createHmac('sha256', this.clientSecret).update(credentials.token).digest('hex'),
                fields: 'id,name,email,first_name,last_name,middle_name,gender,link,locale,timezone,updated_time,verified,picture'
            };

            get('https://graph.facebook.com/v2.3/me', query, (profile) => {

                credentials.profile = {
                    id: profile.id,
                    username: profile.username,
                    displayName: profile.name,
                    name: {
                        first: profile.first_name,
                        last: profile.last_name,
                        middle: profile.middle_name
                    },
                    email: profile.email,
                    picture: profile.picture,
                    raw: profile
                };

                return callback();
            });
 ```

Better yet, it would be cool to allow users to specify the paths of the fields they want to copy out of the profiles into the session objects.

**Comment by pankajpatel** [comment]
you can access the picture by the `raw` as `raw.profile.picture`.

`raw` contains the JSON profile response received.

**Comment by grenager** [comment]
Yes, but picture is not there in the raw JSON, because the code doesn't
request that field from Facebook. See my proposed code changes. Thanks!

Teg

**Comment by pankajpatel** [comment]
@grenager You are right; though there would be many fields which facebook provides which can be included in the query.

I think it will be good to have an option for the provider to accept query param for the default request.

**Comment by grenager** [comment]
Great idea, thanks Pankaj.

**Comment by ricktbaker** [comment]
Any update on this?  Is there any way to make it so it requests the profile image as well?

**Comment by pankajpatel** [comment]
@ricktbaker PR needs to be submitted for this to make profile picture available as well.

**Comment by PaulMougel** [comment]
I just submitted a PR to fix this issue, feedback and comments are welcome 👍

You will be able to specify the fields you want to retrieve from the user's profile, which will be available in `credentials.profile.raw`.
