### ISSUE TITLE
bell with another strategy

### ISSUE THREAD

**Issue by jedireza** [hapijs/bell#30]
I'm looking for a way to layer authentication strategies. For example I'd like someone who's authenticated with `hapi-auth-basic` to also connect a twitter account using `bell`.

Any ideas are much appreciated.

**Comment by ravisuhag** [comment]
@jedireza late in party but i have come up with a solution for this, if you still need it. Not sure how much robust it is, but open to discussion. 
Check here : https://github.com/hapijs/bell/issues/134

**Comment by jedireza** [comment]
@ravisuhag thanks for the update!

**Comment by gerenrot** [comment]
Having the same issue.
I think server.auth.test() should do the trick.

**Comment by marcuspoehls** [comment]
Hi @gerenrot, Hi @jedireza,

I’m running into a related issues as you did. My hapi app allows users to sign up and log in and I’m saving the session using `hapi-auth-cookie`. Now users should connect with GitHub and just want to add GitHub’s API token to the exising user profile (based on `hapi-auth-cookie`).

The `server.auth.test` works if the user already granted access on GitHub for my applicaiton. If the user is requested on GitHub to grant access and the request returns to my application, the `server.auth.test` does not find a valid session.

Did you managed to create a working solution to combine `hapi-auth-cookie` with `bell`?

**Comment by jedireza** [comment]
@marcuspoehls you have a similar goal that I did previously. I never did come up with a solution though.

**Comment by gerenrot** [comment]
You should have an endpoint with a GitHub auth strategy (bell scheme).
Redirect the user to this endpoint. He might be further redirected to GitHub to grant access and then redirected back.
When he's back and authenticated with GitHub auth, use server.auth.test() to get his account details and add the GitHub profiles to his account.

**Comment by marcuspoehls** [comment]
@gerenrot @jedireza Thanks for your help!

@gerenrot That's what I did and everytime the user is required to grant access on GitHub, the `server.auth.test()` fails. If the user already granted access on GH, everything goes smooth.

I found a workaround by saving a cookie using it within the bell callback. Will write a tutorial on that and share it here for everyone interested and having the same issues.

**Comment by gerenrot** [comment]
Does hapi see the sid cookie in the failed scenario?

**Comment by marcuspoehls** [comment]
@gerenrot No

**Comment by gerenrot** [comment]
Why? In what url the server sees sid? In what url it does not? Whats the difference? Maybe it's the cookie isSecure setting?

**Comment by marcuspoehls** [comment]
@gerenrot No idea. The server sees the `sid` on all other routes that require the `session` strategy (based on `hapi-auth-cookie`). The one where hapi doesn’t see it is the one that requires `github-bell` auth.

Have also checked the `isSecure` setting for the cookie and set both to `false` for my development setup.

Haven’t found the issue yet. Even setting a custom cookie with `reply.state` on a `session` route, it’s not available on the route where `github-bell` is required.

**Comment by dpmott** [comment]
@marcuspoehls Be advised that bell does a series of redirects, and there are some associated bugs wherein a cookie doesn't survive a second redirect.

https://github.com/hapijs/hapi-auth-cookie/issues/159
https://github.com/request/request/issues/1502
https://bugs.chromium.org/p/chromium/issues/detail?id=150066

**If this is your issue**, then I recommend doing something like this in your route handler:
`request.cookieAuth.set({ sid: id });`
`reply('<html><head><meta http-equiv="refresh" content="0; url=/" /></head></html>');`

This will ensure that the cookie survives the refresh.

**Comment by marcuspoehls** [comment]
@dpmott Hey David, thank you for your explanation and links. I’ve found a “solution” or workaround to get things working. Will use your recommendation when working on it the next time. Thanks again buddy!

**Comment by gerenrot** [comment]
@marcuspoehls, just stumbled upon an issue similar to yours. It was working just find before. Debugging revealed my issue is due to an upgrade to the latest hapijs and its default setting of [SameSite=Strict](https://github.com/hapijs/hapi/issues/3323). 

It does say 'Breaking Changes' :)

Can that be related to the issue you are having?
