### ISSUE TITLE
auth with multiple strategies

### ISSUE THREAD

**Issue by roytz** [hapijs/bell#300]
Hi,
If I use bell for multiple logins, lets say Facebook and Twitter, how can I use both of them as the auth of other routes? I posted an example below -

```
exports.register = function (server, options, next) {

    plugin.route({
        method: 'GET',
        path: '/users/authorizedPage',
        config: {
            auth: {
                strategies: ['facebook', 'twitter'] // this doesn't work
            }
        },
        handler: function (request, reply) {
            reply('You are authorized to see this page');
        }
    });

    next();
};


exports.register.attributes = {
    name: 'users-authorized'
};
```

**Comment by ldesplat** [comment]
The most common use case is that you allow a user to authorize themselves with certain providers but that you have your own way of having sessions. So with bell, you can have a different path for each provider and you just redirect back to your authorizedPage when done.

See https://bell.now.sh/_src/?f=index.js&h=2372%3B1573 for an example of doing that (separate page for each provider). Then you can use something like hapi-auth-cookie to keep track of your user's authentication status or the many other ways that one can use.

**Comment by roytz** [comment]
Thank you @ldesplat
