### ISSUE TITLE
twitter example

### ISSUE THREAD

**Issue by jerome724** [hapijs/bell#304]
Hey, in the Twitter example there is a clientId and clientSecret, i was a bit confused because in twitter you have only the ``consumer_key``, ``consumer_secret``, ``access_token`` and the ``access_token_secret``. Which on of these is the right one?

**Comment by dstevensio** [comment]
If I recall correctly, it's:

`clientId` -> `consumer_key`

`clientSecret` -> `consumer_secret`

**Comment by jerome724** [comment]
Yep, that worked, thank you!
