### ISSUE TITLE
Google refreshToken returns undefined

### ISSUE THREAD

**Issue by samx** [hapijs/bell#317]
Bell API authentication doesn't return the refreshToken for me. Wondering if this is a bug or maybe I missed something.

Options I passed in:
```
options: {
         bell: {
                provider: 'google',
                isSecure: false,
                password: 'password‐that‐is‐at‐least‐32‐chars',
                clientId: '...',
                clientSecret: '...',
                scope: ['profile', 'email']
            }
        }
```

**Response received** 
```

{ 
provider: 'google',
  token: 'ya29...',
  refreshToken: undefined,
  expiresIn: 3600,
  query: {},
  profile:
   { id: '1234567',
     displayName: 'samx10',
     name: {...},
     email: '...',
     raw:{...}
}

```

**Comment by AdriVanHoudt** [comment]
If the user is already authenticated with google and your app and does the auth flow again (for login for example) you won't get a refresh token.
It is documented somewhere but can't find it atm.

**Comment by thebillkidy** [comment]
Just had the same issue. Google will need you to revoke the app access to get the refresh_token again. They only provide this during the first authentication flow.

To force this behavior, you can use the following providerParams:

```javascript
providerParams: {
    access_type: "offline",
    prompt: "consent"
}
```

like this:
```javascript
server.auth.strategy("google", "bell", {
    provider: "google",
    password: "<cookiepass>",
    clientId: "<clientid>",
    clientSecret: "<clientSecret>",
    scope: ["<yourscopes>"],
    isSecure: false, // Terrible idea but required if not using HTTPS especially if developing locally
    forceHttps: true,
    skipProfile: true,
    // Add custom provider params to always get a refresh token
    providerParams: {
        access_type: "offline",
        prompt: "consent"
    }
});
```

**Comment by AdriVanHoudt** [comment]
Well `prompt: "consent"` is kinda a hack. This forces the consent screen every time you authenticate, which you might want or not. I'm not even sure that behaviour is documented.

**Comment by thebillkidy** [comment]
This is why I added the whole reply, stating that Google gives it the first time during authentication :) + I think on Applications that you make, this so called "hack" is necessary

**Comment by AdriVanHoudt** [comment]
Well Google states that you need to store the refresh token. So `necessary` depends on your use case.
