### ISSUE TITLE
Using bell for custom API with jwt tokens (no cookie use) ?

### ISSUE THREAD

**Issue by mmc41** [hapijs/bell#320]
The bell documentation states that bell must be combined with something else to maintain state which is fine since I want to use JWT tokens for my REST api. However all the examples I can find point to cookies and the configuration object for setting up the bell strategy seems to require some cookie-specific required parameters like password and isSecure. Is it possible to change this so my API can use bell for authentication than switch to using JWT tokens (without using cookies)?

**Comment by ldesplat** [comment]
This is 3 months late but for anybody searching for this. Yes, it is exactly how bell is supposed to be used. The cookie options you can set on Bell is only for its own use. Once you get all the information, you are supposed to use your own mechanisms. So cookie/JWT/Authorization header based is all fair game.
