### ISSUE TITLE
More more more [Auth suggestion]

### ISSUE THREAD

**Issue by Extarys** [hapijs/bell#322]
Comm: We could add Twilio and **Plivo** support :D
Gaming: Steam
Hosting: Vultr

Just suggestions.

**Comment by AdriVanHoudt** [comment]
@Extarys PR's welcome! 🎉

**Comment by Extarys** [comment]
YAY I'll try :P

**Comment by AdriVanHoudt** [comment]
If you need any help or any question just shoot!

**Comment by Extarys** [comment]
Thanks! I'll try finishing my thousand project I started though I'll bookmark and come back ;)

**Comment by AdriVanHoudt** [comment]
I know the pain :D
