### ISSUE TITLE
How to call from frontend?

### ISSUE THREAD

**Issue by JosephDuffy** [hapijs/bell#323]
I am trying to use Bell to integrate Slack login. We have a Hapi API with a React frontend.

If I access /auth/slack directly the regular Slack login flow works and I am redirected back to my API, with everything working as expected. However, the user should not be viewing the API.

To get around this I have the strategy setup as follows:

```js
server.auth.strategy('slack', 'bell', {
  provider: 'slack',
  password: 'our_pass',
  clientId: 'our_client_id',
  clientSecret: 'our_client_secret',
  providerParams: {
    team: 'out_team_id',
  },
  forceHttps: true,
  isHttpOnly: false, // Support authentication using the `fetch` API
  location: (request: Request) => {
    if (request.query.redirect) {
      return request.query.redirect;
    } else {
      return '';
    }
  },
});

server.route({
  method: 'GET',
  path: '/auth/slack',
  config: {
    cors: {
      origin: ['*'],
      credentials: true,
    },
    auth: {
      mode: 'try',
      strategy: 'slack',
    },
  },
  handler: (request, reply) => {
    if (!request.auth.isAuthenticated) {
      reply(Boom.badRequest(request.auth.error.message));
      return;
    }

    const { profile } = request.auth.credentials;

    if (!profile.raw.ok) {
      reply(Boom.badRequest(profile.raw.error, profile));
      return;
    }

    // Create/update user in database...
    return user;
  },
});
```

Note that `isHttpOnly` is set to `false` to enable sending the cookie using the `fetch` API.

To login with the client we send the user to the API directly, but pass a `redirect` query parameter, which is used by the function above to tell Slack to redirect the user to the frontend once authenticated.

On the page that Slack redirects the user to I have created the following function to try and log the user in:

```js
const { queryString } = params; // This is the ?code=...&state=... part
const initialRessponse = await fetch(`${apiBaseURL}/auth/slack${queryString}`, {
  redirect: 'error',
  credentials: 'include',
});

const contentType = initialRessponse.headers.get('content-type');
if (contentType && contentType.startsWith('text/html')) {
  const html = await initialRessponse.text();
  // Yes this is nasty :)
  const url = html.split(`<meta http-equiv="refresh" content="0;URL='`)[1].split(`'"></head>`)[0];

  const redirectedRes = await fetch(url, {
    redirect: 'error',
    credentials: 'include',
  });

  return handleResponse(redirectedRes);
} else {
  return handleResponse(initialRessponse);
}

async function handleResponse(res: Response) {
  if (res.status !== 200 && res.status !== 201) {
    throw new Error(`Server error: ${res.status} ${res.statusText}`);
  }

  const user = await res.json();

  return user;
}
```

I realise I may be going about this all wrong, but this always leads to the `request.auth.credentials.profile` to be:

```js
{ access_token: undefined,
  scope: undefined,
  user_id: undefined,
  user: undefined,
  raw: { ok: false, error: 'not_authed' } }
```

Any help or pointers in the right direction would be much appreciated!

**Comment by fjoalland** [comment]
I have the same problem, I don't get how to resolve it. Because even if we use "window.open('')", it will be useless we can't catch the profile information.

Did you find some way?

**Comment by JosephDuffy** [comment]
Unfortunately I was using this at my job and I have not continued development. I would still love to know a solution to this for the future/if I get a chance to work on the project again!

Luckily we only really needed to "secure" it by ensuring a user is part of our Slack, which it works adequately for, but we can not differentiate between users.
