### ISSUE TITLE
Discord provider scope issue

### ISSUE THREAD

**Issue by Niputi** [hapijs/bell#326]
The discord provider does not really care if the scopes are changed.
The provider only supports `email` and `identify`. If one of them were to be removed it does not even affect the returned data
what I mean by this is that if I were to add the scope `guilds` the returned data does not change since the provider does not include the [current user guild url](https://discordapp.com/developers/docs/resources/user#get-current-user-guilds). 
Would it be possible to use several get requests?

**Comment by hueniverse** [comment]
I have no idea what this means. Can you provide more details?
