### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hueniverse** [hapijs/bell#329]
This module needs a new maintainer to clear issues and bring it back to the hapi.js standard.

**Comment by ldesplat** [comment]
That would be much appreciated.

**Comment by hueniverse** [comment]
I'm taking over this module for the time being. I don't want to keep it so a new full time maintainer is still needed, but this is too important to the ecosystem to leave unresolved for this long.

I am very thankful to @ldesplat for his work on this module all this time. He has done a great job moving it forward, setting a great standard to be continued.

**Comment by wswoodruff** [comment]
Thank you @ldesplat!!
