### ISSUE TITLE
Using bell with Nginx Reverse Proxy

### ISSUE THREAD

**Issue by captainjackrana** [hapijs/bell#331]
I'm currently trying to use Nginx for my hapi server which has bell installed. 
Basically Nginx listens on port `80` & `443` for `HTT`P & `HTTPS` traffic and routes it to the hapi server listening on `localhost:3000`
After setting up Nginx, bell now sends `redirect_uri` param to 3rd party login providers ( facebook, linkedin) as `localhost:3000`. So, after authentication, users get redirected to the `localhost` address instead of my domain, which is incorrect.

Is there any standard on how a reverse proxy is to be used with bell?

**Comment by timcosta** [comment]
You can set a custom hostname for your Hapi server. https://hapijs.com/api#serverinfo

**Comment by captainjackrana** [comment]
@timcosta are you referring to something like 
`const server = new Hapi.Server();
server.connection({ port: 3000, host: example.com });`

**Comment by timcosta** [comment]
@captainjackrana you can use the `location` option at the bottom here: https://github.com/hapijs/bell/blob/master/API.md#options

**Comment by captainjackrana** [comment]
Yes i'd seen that option before but i was hoping I wouldn't have to resort to that. Anyway, looks like its the only way out for now :(
