### ISSUE TITLE
Bell 9.0.0 Release Notes - Draft

### ISSUE THREAD

**Issue by ldesplat** [hapijs/bell#333]
## Summary

This release upgrade Bell to use Hapi 17 and Node 8+. This means heavy use of async/await over callbacks.

## Breaking Change

- Hapi 17
- Node 8+

## Other Changes in this Release

---

Hapijs organization uses Milestones to track changes. Even though major releases, warrant release notes, you can access all the previous releases and changes here: https://github.com/hapijs/bell/milestones?state=closed

Thank you everyone!

**Comment by rapoell** [comment]
see my comment in [hapiv17 support](https://github.com/hapijs/bell/issues/330)

**Comment by tangkhaiphuong** [comment]
When this features is release?
