### ISSUE TITLE
Getting Error: Lifecycle methods called before the handler can only return an error, a takeover response, or a continue signal

### ISSUE THREAD

**Issue by dharmax** [hapijs/bell#341]
i moved to hapi 17 and i'm using the bell hapi17 branch.
i can't get Bell  to work (and it worked before).
This is the routing:
`
{
        method: ['GET', 'POST'],
        path: '/login/google',
        config: {
            auth: 'google',
            handler: async (request, h) => {
                if (!request.auth.isAuthenticated)
                    return {error: 'Authentication failed due to: ' + request.auth.error.message}

                let creds = request.auth.credentials
                try {
                    let session = await handleSSOLogin('google', creds.profile.id, creds.token, creds.profile.raw)
                    return h.redirect(`/post-login.html?sessionToken=${session.token}`)
                } catch (e) {
                    return h.redirect(`/post-login?errorType=${e.errorType}&error=${e.error}`)
                }
            }
        }
    },
`
Now, when i call this API the lifecycle error message is fired. Other API calls (i have password authentication, too, that doesn't work with Bell) do work fine. Here, it doesn't reach the handler method.

Expected behavior:
The handler code should be reached.

**Comment by hueniverse** [comment]
Try version 9.
