### ISSUE TITLE
Failed obtaining linkedin user profile

### ISSUE THREAD

**Issue by captainjackrana** [hapijs/bell#342]
I've been using bell v8.5.0 to authorize Linkedin logins for some months now without facing any issues. However, since the last few days, its been throwing the following error in my app - 
`Failed obtaining linkedin user profile`

As directed in issue https://github.com/hapijs/bell/issues/141, I put a `console.log` on the response object at https://github.com/hapijs/bell/blob/master/lib/oauth.js#L297 which reveals the following -

`statusCode:500, statusMessage: 'Internal Server Error'`

Now I haven't touched the linkedin app settings or my own app for quite a while, so i'm not sure why this would happen suddenly. Even tried updating bell to v8.9.0 but without any success

**Comment by PaulMougel** [comment]
It looks like LinkedIn is having issues with OAuth, see [this link](http://status.auth0.com/incidents/6xtmprjjt9cb) or [this other link](https://stackoverflow.com/questions/48297743/did-the-linkedin-api-change-today).

**Comment by captainjackrana** [comment]
I've commented out the `current-share` field from the Linkedin API call and its working perfectly now.. Thanks @PaulMougel and will keep track of the OAuth issue
