### ISSUE TITLE
Google | Error when requesting with scope for YouTube

### ISSUE THREAD

**Issue by agchou** [hapijs/bell#346]
I'm getting the an error when adding any youtube scope—things work fine when I comment out scope. I also got an error around a cookie. Any thoughts?

## Error: 
```
Debug: auth, unauthenticated, error, youtube
    Error: Failed obtaining google user profile
    at get (/usr/shopwith/api/node_modules/bell/lib/oauth.js:321:28)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## Strategy
```
    server.auth.strategy('youtube', 'bell', {
      provider: 'google',
      password: 'some_password',
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      isSecure: process.env.NODE_ENV === 'production',
      scope: [
        // 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly',
        // 'https://www.googleapis.com/auth/yt-analytics.readonly',
        // 'https://www.googleapis.com/auth/youtubepartner',
        'https://www.googleapis.com/auth/youtube',
      ],
      providerParams: {
        access_type: "offline",
        prompt: "consent"
      }
    });
```

**Comment by agchou** [comment]
Figured it out! When I specified my own scopes it overrode the default `scope: ['profile', 'email']` which is necessary for the to retrieve the profile from google.

Should the behavior instead be to add the scopes defined in the strategy to the required scopes so this error can be avoided? Or have it added to be more explicit in the documentation somewhere?

**Comment by hueniverse** [comment]
It would be nice to have an `extraScope` that will work the way you suggests, but I am not going to change the defaults. If someone wants to add that functionality, I'll review.
