### ISSUE TITLE
Usage without a strategy

### ISSUE THREAD

**Issue by davidjamesstone** [hapijs/bell#353]
From the docs:

`bell` exposes an oauth object in its plugin as `server.plugins.bell.oauth`. Calling the v2 method with all the settings documented above, will handle the oauth2 flow.

I'm trying to use this approach to connect to and OpenID Connect service. OpenID Connect is for authentication and is based on the `OAuth2` authorization protocol.

The issue I am encountering is around the `authenticated` and `unauthenticated` methods on the toolkit object `h`. If I call the following within the `redirect_url` (i.e. the return url) route handler:

```
server.plugins.bell.oauth.v2(request, h)
```

`bell` complains that `h.authenticated`  is not a function. I can see why as these two methods are only added to the toolkit under certain circumstances.

I can't find any example of this kind of usage for hapi v17.
Has anyone been able to get this to work?

I hope this makes sense. Thanks in advance.

**Comment by hueniverse** [comment]
It was never designed to be used directly. The object is exposed for the OAuth 1 client.
