### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by Asuza** [hapijs/bell#357]
The default error, "Failed obtaining facebook access token" could be more useful. Logging the provider settings, payload, and the _www-authenticate_ header would help immensely when trying to resolve authentication issues.

I spent a stupid amount of time trying to understand what was wrong with my code until I realized that I needed to dig down and add my own debugging statements.

Below is the following change I made for debugging in _oauth.js_:
```javascript
        // Obtain token
        try {
            var { res: tokenRes, payload } = await Wreck.post(settings.provider.token, requestOptions);
        }
        catch (err) {
            console.warn({
                provider: settings.provider,
                requestOptions: requestOptions,
                error: err.data.headers['www-authenticate']
            });
            // return h.unauthenticated(Boom.internal('Failed obtaining ' + name + ' access token', err), { credentials });
            return h.unauthenticated(Boom.internal(err.data.headers['www-authenticate'], err), { credentials });
        }
```

**Comment by AdriVanHoudt** [comment]
Makes total sense.
Doing a 'rogue' console.warn does not seem like the right solution, what if we attach the extra info on the error object?

**Comment by Asuza** [comment]
I agree, a rogue `console.warn` would not be ideal. I wanted to clearly show where I had put it and what data was useful to me.

Attaching it to the error object makes sense (with documentation somewhere), and adding the _www-authenticate_ contents to the `Boom` message would be really helpful as well.

**Comment by AdriVanHoudt** [comment]
I prefer concise error messages with a bunch of structured data but if you have a way to integrate the header into the message then for sure do it.
Are you willing to open up a PR for this?

**Comment by Asuza** [comment]
It won't be today, but I'll try to open one in the near future.

**Comment by AdriVanHoudt** [comment]
Awesome! 💪

**Comment by Asuza** [comment]
Created PR #359.

**Comment by Asuza** [comment]
I tried to figure out where/how a new test should be added, but being completely unfamiliar with it, it's hard to know where to start.

**Comment by AdriVanHoudt** [comment]
No progress on the PR
@Asuza if you still want this, just comment on the PR or make a new one
