### ISSUE TITLE
support android app sign in

### ISSUE THREAD

**Issue by quytang** [hapijs/bell#361]
The google provider doesn't support this one:
https://developers.google.com/identity/sign-in/android/backend-auth

Would you mind telling me how to get it worked?

**Comment by AdriVanHoudt** [comment]
AFAIK on android you need to do a client side oauth flow like in the article and then exchange/verify the token on your server (see more to the bottom of the article).

**Comment by quytang** [comment]
Thanks @AdriVanHoudt!
I've just created an API in this case. However, It would be nice if bell also supports it.

**Comment by AdriVanHoudt** [comment]
Do you have a suggestion on how that would look in Bell?

**Comment by quytang** [comment]
I think it should be a configuration flag for google provider.
For example:
```
server.auth.strategy('google:mobile', 'bell', {
    appType: 'mobile',
    ...
  });
```

**Comment by AdriVanHoudt** [comment]
I thought about this and I don't thinks this really fits into Bell.
The mobile option would be completely other thing from the current Bell stuff.
The only thing it would do is make a strategy that calls a provider function. There is not really an oauth flow in that.
To be correct you'd also use the `google-auth-library` lib which is not really a dependency I want to add.
If you want I can give you an example of how you might be able to make your own strategy that does this.
Does this make sense?

**Comment by quytang** [comment]
Thank you very much @AdriVanHoudt, I've already done one. So I will close the issue.
I attach the code snippet here to help those who face the same issue.

```
const Boom = require('boom');
const { OAuth2Client } = require('google-auth-library');

const client = new OAuth2Client(
  CLIENT_ID,
  CLIENT_SECRET
);

server.auth.strategy('session', 'cookie', {
      password: SECURE_KEY,
      cookie: AUTH_TOKEN_KEY,
      isSecure: false,
      validateFunc: async (request, session) => {
          const cached = await cache.get(session.sid);
          const out = {
              valid: !!cached
          };

          if (out.valid) {
              out.credentials = cached;
          }

          return out;
      }
  });

server.route({
    method: 'GET',
    path: '/auth/mobile/google',
    config: {
      auth: {
        strategy : 'session',
        mode     : 'try'
      },
      handler: async function(request, h) {
        let user = undefined
        if (request.auth.isAuthenticated) {
          user = request.auth.credentials.user
          return { data: { user } };
        }

        const { idToken } = request.query;
        if (!idToken) {
          return Boom.badRequest('Missing idToken parameter');
        }

        const ticket = await client.verifyIdToken({
          idToken,
          audience: CLIENT_ID
        });

        const payload = ticket.getPayload();
        const { sub: googleId, email, name: displayName, picture } = payload
        user = {
          googleId,
          email,
          displayName,
          picture
        };

        const sid = `${googleId}.${email}`;
        await request.server.app.cache.set(sid, { user }, 0);
        request.cookieAuth.set({ sid });
        return { data: { user }};
      }
    }
  });
```

**Comment by AdriVanHoudt** [comment]
If more people want this we can still reconsider this ofc. 👌 
Thanks for understanding and posting the snippet for others!
