### ISSUE TITLE
Preserve URL Hash Fragment During Auth

### ISSUE THREAD

**Issue by ilyaigpetrov** [hapijs/bell#365]
If it's possible, please, preserve url hash fragment (#foobar, e.g) during auth.

### Why

1. Unauthorized users of `/protected#foobar` are redirected by my server to `/login?redirect_to=/protected#foobar`. The server doesn't see #foobar part, instead it is preserved by the browser during redirect.
2. `/login` launches bell's google strategy auth flow which removes #foobar.
3. After successful login user is redirected to `/protected#`, foobar is lost.

I want #foobar to be preserved by bell, otherwise I will have to recourse to JavaScript redirects.

### UPD

Also, if possible, don't paste empty hash, e.g. `/login#`, after successful login if there were no such hash before.

**Comment by AdriVanHoudt** [comment]
Check if the `location` setting might be able to help you

**Comment by ilyaigpetrov** [comment]
`location` header is used during server redirects and it may include hash fragment.
The problem is:

1) Initial hash fragment is not passed to the server and not preserved during auth, so currently I do redirect with client javascript packing hash fragment to a query string parameter `login?redirect_to_relative=foo#bar` (but percent-encoded). I wish hash value were preserved and restored after auth by bell automatically.
2) Server may `h.redirect` to `foo#bar`, but if hash is empty and you `h.redirect('foo')` then after auth Bell appends hash to the url, e.g. `localhost/foo#`, which is not desirable.

**Comment by AdriVanHoudt** [comment]
Am I correct that you
* go to `login?redirect_to_relative=/protected?abc=xyz#bar` and you end up at `/protected?abc=xyz#`?
* go to `login?redirect_to_relative=/protected?abc=xyz` and you end up at `/protected?abc=xyz#`
?

**Comment by ilyaigpetrov** [comment]
1. First is true if I don't pack hash into a percent-encoded query parameter (via script in browser). Yes, you are right.
2. Second is true also.

**Comment by hueniverse** [comment]
The server doesn't see the fragment. There is no way to preserve it. You need to implement something on the client to keep track of it.
