### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by rinick** [hapijs/bell#367]
I tried this:
```
git clone
npm install
modify examples/twitter.js to add my clientId and clientSecret
node examples/twitter.js
```
open `http://localhost:8000/bell/door` in browser 
response: `{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`

am I doing anything wrong?
btw, I'm using node v10.4.0

**Comment by AdriVanHoudt** [comment]
Do you see the server printing anything more specific?
As in is it Twitter returning the 500 or is the `JSON.stringify` in the example failing for example.

**Comment by rinick** [comment]
sorry, yes, it works.
I didn't update my callback url in the twitter app setting

**Comment by AdriVanHoudt** [comment]
Glad you got it working!
