### ISSUE TITLE
Integration with Facebook, Android, Web

### ISSUE THREAD

**Issue by ashrafk786** [hapijs/bell#369]
## Context
I have a single page application written in Angular1 and we're in the process of releasing an android app.  The angular app allow login and registration using your email address. We'd liked to have social integration - starting with facebook.  We've enabled bell and i have a separate route for login using facebook. When a user clicks on the login with facebook link, I target a new window, hit the `/v1/auth/facebook/login` and everything works as expected. We're having some challenges when it comes to the mobile App.

We tried having the android app hit our backend `https://dapi.mysite.com:8000/v1/auth/facebook/login` but it fails because oAuth2 does a redirect to the provider and that fails in the android app since its not being done in a browser. However, if I have the android sdk hit facebook like the example shows, I receive a token and the scope data that I need.

I need help in understanding how to integrate both the web and the android with social. Should I create a new route that takes in a payload of token and id and have it hit the facebook api to validate what was sent and create a session/cookie? If this is the best way forward, can i use bell to do the validation of the token or should I use a different tool?

Thanks in advance.

Below is my facebook login code:
```
exports.facebook = {
	auth: 'facebook',
         handler: function (request, reply) {
			models.User.findBySocialNetwork(
				request.auth.credentials.provider,
				request.auth.credentials.profile.raw.id
			).then(function (userRecord) {
				if (userRecord){
					var result = internals.generateSessionObject(userRecord);
					request.server.app.cache.set( String(result.id), { user: result }, 0, (err) => {
						if (err) {
							reply(err);
						}
						request.cookieAuth.set({id: result.id });
						winston.log('info', 'auth.facebook', {
							loggedin_username: result.username
						});
						return reply ({user: result});
					})
				}else{
					return Promise.reject(
						Boom.badRequest(
							"Unable to locate your "+ request.auth.credentials.provider +
							" account. Please register." ,
							{
								field:'network',
								value:request.auth.credentials.provider
							}));
				}
			}).catch(function(error){
				return reply(error);
		  })
    }
};
```

**Comment by AdriVanHoudt** [comment]
Hey @ashrafk786, 

If I understand correctly you are trying to use the bell flow in your native Android app? If so I don't think that will work for you.
Bell does indeed do redirects. I think you probably want to look into using the Facebook android sdk https://developers.facebook.com/docs/facebook-login/android/

**Comment by ashrafk786** [comment]
@AdriVanHoudt Our backend requires that you authenticate in order to access most endpoints. Once authenticated, we create/set a cookie. The native app is able to authenticate against facebook using their SDK but they have not authenticated against our backend and I was looking for guidance on how to proceed. Should I create a new route for mobile that take a provider, id, token, does a lookup against the db to find the record, and then using facebook javascript sdks or hellojs, validate the token and then send the cookie back to the app for it to send along with each subsequent request?

**Comment by AdriVanHoudt** [comment]
afaik, you should get a token from the client side Facebook auth flow.
You send that token to your api which then trades that token with the Fb api for credentials (not 100% sure but I think you trade the client token for the actual access and refresh token and the user info).
Once you have that you can set your personal authentication cookie on the response and your client will be able to use it to authenticate on other calls.
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/#confirm might help

**Comment by ashrafk786** [comment]
@AdriVanHoudt So I was thinking along the same lines and I want to know where does Bell fit into this picture for this use case? Do you recommend I use a different library for this purpose?

**Comment by AdriVanHoudt** [comment]
Good question, for me Bell is a solution for server side web oauth flows.
Maybe we should make that more clear in the readme?

**Comment by ashrafk786** [comment]
@AdriVanHoudt Do you have a suggestion on how I can use bell without the `web flow` component? What If I simply want to call `bell.facebook.validate(token)` and have it do a validate the token and provide me with the profile data? It seems if the logic in bell was abstracted, it would work for a web-flow and a server side check.
