### ISSUE TITLE
State parameter, nonce, in-app browser and PWA

### ISSUE THREAD

**Issue by hsablonniere** [hapijs/bell#370]
Hello Bell team :wink:

Thanks very much for this project!

## Context

We've been using bell on a side project for a few weeks now to let our users authenticate with Google, FB and Twitter. It's a responsive website available on desktop, tablet and mobile.

We've identified two situations on mobile where our authentication process fails.

### Situation 1

* Browse the site on mobile with a browser like Chrome for Android
* Click on login with Facebook
* When the Facebook native app is installed, the login process starts in the native app.
* After the login process, Facebook does not redirect to the original browser, it loads the redirect_uri inside its in-app browser.

Facebook's in-app browser does not have access to the original `bell-facebook` cookie containing the state/nonce. It does not share any state with the original browser used to load the site.

### Situation 2

* Browse the site on iOS Safari
* Add the site to the homescreen and click on the shortcut
* Click on login with Facebook
* The login process will start outside of the "homescreened" site and will end up in Safari.

Again, it seems like the original `bell-*` cookie containing the state/nonce is not shared between a site added to homescreen and Safari.

## Questions about bell and the `state` param

From what I've seen in the code, bell really went into the details to protect its users. It generates a nonce, stores it locally in a cookie, passes it via the `state` param to the oAuth site and then verifies it after at the end of the dance.

I read a few articles and it seems like this is a great way to protect against CSRF attacks when using oAuth2. https://tools.ietf.org/html/draft-ietf-oauth-v2-threatmodel-06 (4.4.1.8)

In the 2 situations I described this protection is preventing my users to login on mobile.

1. Did any of bell's user complain of this behaviour?
2. I enabled the strict whitelisting of URLs used for redirection, do I still need this kind CSRF protection using nonce + state and a cookie?
3. Maybe we could generate a nonce, sign it as a JWT (or do what iron does), pass it as the `state` param and check it back after the dance to verify if it came from us. WDYT?

Sorry if this was long but I tried to give all the context and details so we can discuss this.

Cheers :smile: 
Hubert

**Comment by AdriVanHoudt** [comment]
Oh, those are some interesting questions.

Situation 1: I honestly don't know. Doesn't facebook have any docs oh how to properly use their native app for web logins on mobile?

Situation 2: Interesting, are you opening the flow in another window, if so maybe try just using the current window?

If I may, I will redirect the questions of the state param to @hueniverse (or anyone else for that matter), I did not implement the original flow nor do I feel confident enough to speak about CSRF attacks and the security implications.

**Comment by hueniverse** [comment]
I am not sure there is an easy way around this. bell needs a way to verify that the client coming back with the credentials is the same one who started the workflow and it uses cookies to maintain that state. Whitelisting domains is not enough. This is a limitation of the OAuth web flow. If I can trick someone into opening your return endpoint with compromised credentials, I can get them to reveal private information to an account under my control (e.g. link their data to an account on your site that I control instead of the account they control).

I don't know how to solve this when cookie state is not preserved across the workflow.
