### ISSUE TITLE
`handler` is not called when authentication failed in twitter provider.

### ISSUE THREAD

**Issue by lazex** [hapijs/bell#371]
I try example written in readme, and change `hanlder` code to below.

```
handler: function (request, h) {
    console.log("handler called")
    if (!request.auth.isAuthenticated) {
        console.log("failed")
        return h.redirect('/autherror')
    }

    return h.redirect('/home')
},
```

It works when authentication successed.
However, it does not work when authentication failed by clicking cancel button in twitter page.

I got this response.

```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

And, no logs are shown in console, which means that handler is not called.

How can I handle it?

**Comment by AdriVanHoudt** [comment]
you probably want your route config to look like
```js
            auth: {
                mode: 'try',
                strategy: 'twitter'
            }
```
the important part being the `mode`, see https://hapijs.com/api#-routeoptionsauthmode

**Comment by lazex** [comment]
It works. Thank you!
