### ISSUE TITLE
Document how to handle user pressing the back button

### ISSUE THREAD

**Issue by sholladay** [hapijs/bell#377]
Users make mistakes and sometimes hit the back button in an effort to redo their work. If a user who just logged in hits the back button, such that they end up back at the login page that bell sent them to, even if they enter the same credentials again bell will return an error saying "Missing ___ request token cookie".

It would be useful to document the correct way to handle this case.

**Comment by AdriVanHoudt** [comment]
Do you know the correct way to handle this?
PR's to the docs are always welcome for sure! ✨

**Comment by sholladay** [comment]
No, sadly. I don't have any ideas. I vaguely remember Eran saying it would involve multiple auth strategies. But I don't know how that would help. I think the main problem is that a new `state` patsmeter would have to be generated. Perhaps some kind of redirect is necessary?

I do think this is important for good UX.

**Comment by AdriVanHoudt** [comment]
yeah it doesn't like something we can do easily.
Maybe we can start with a failing test or gist/repo with a failing case and we can go from there?

**Comment by hueniverse** [comment]
Double auth strategies help when the login is blind, not if there is an actual middle page. In those cases, I have seen sites manipulate the browser navigation and stuff like that to move the user back to the sending endpoint which should already detect a logged in state.
