### ISSUE TITLE
Generic OIDC provider

### ISSUE THREAD

**Issue by JbIPS** [hapijs/bell#382]
Hello,

I recently implemented a generic OpenID-Connect auth strategy and I was wondering if it could/should be part of Bell.

Some information about my implementation:
* based on [openid-client](https://www.npmjs.com/package/openid-client)
* user only need to set a discovery URL, a cliend ID and a secret (and scope maybe)

I looked around a bit and just found https://github.com/gaaiatinc/hapi-openid-connect talking about OIDC, but it seems like it's a server implementation.

So, is it a good fit for Bell you should I just create another lib?

Thank you :smiley:

**Comment by AdriVanHoudt** [comment]
Sure 🎉  PR's always welcome!
