### ISSUE TITLE
using bell in rest api built in hapi and front end built in react

### ISSUE THREAD

**Issue by hrithick** [hapijs/bell#387]
i am building rest api using Node js (with Hapi framework). 

in front end i used react-google-login . i pass clientId , Secret to that component when i clicks it promts google auth page and after giving permissions. it returns accesstoken , profileObj etc.

so now instead of registering auth strategy as google in hapi  can i able to pass the accesstoken i get from
frontend and get the profileInformation from google using bell in the backend.

```javascript
const internals = {};
internals.start = async function () {

    const server = new Hapi.Server();
    server.connection({
      host : "localhost",
      port : 8000,
    })
    await server.register(Bell);

    require('./src/oauth/index')(server);
    
    server.auth.strategy('facebook' ,'bell' ,{
      provider: 'facebook',
      password: 'cookie_encryption_password_secure',
      isSecure: false,
      clientId: '3600000026089764',
      clientSecret: 'FFF7yd7shdBUGg75f6',
      location: server.info.uri 
    });

    server.auth.strategy('google', 'bell', {
        provider: 'google',
        password: 'cookie_encryption_password_secure',
        isSecure: false,
        clientId: 'ogleusercontent.com',
        clientSecret: 'L*********dsaRG',
        location: server.info.uri 
    });
  
    // i want to do like this 
    server.route({
        method: 'POST',
        path: '/signInWithGoogle',
            handler: async function (request, h) {
              console.log(request.payload.access);
              const {res , payload } = await Wreck.get('https://www.googleapis.com/plus/v1/people/me',{
                headers: {
                    'Authorization' : `Bearer ${request.payload.access}`,
                    'content-type': 'application/x-www-form-urlencoded'
                } 
               })
               console.log(payload.toString());
            }
    });
        //instead of doing like this
        server.route({
          method: 'get',
         path: '/signInwithFacebook',
         config: {
          auth: {
              strategy: 'facebook',
              mode: 'try'
          },
          handler: function (request, h) {
              console.log(request.auth);
              if (!request.auth.isAuthenticated) {
                  return h.response('Authentication failed due to: ' + request.auth.error.message);
              }
              return h.response(JSON.stringify(request.auth.credentials, null, 4));
          }
      }
     });
```

**Comment by hrithick** [comment]
[ds.txt](https://github.com/hapijs/bell/files/2591476/ds.txt)

**Comment by hrithick** [comment]
`'use strict';

const Bell = require('bell');
const Hapi = require('hapi');
const Wreck = require('wreck');

const internals = {};


internals.start = async function () {

    const server = new Hapi.Server();
    server.connection({
      host : "localhost",
      port : 8000,
    })
    await server.register(Bell);

    // You'll need to go to https://console.developers.google.com and set up an application to get started
    // Once you create your app, fill out "APIs & auth >> Consent screen" and make sure to set the email field
    // Next, go to "APIs & auth >> Credentials and Create new Client ID
    // Select "web application" and set "AUTHORIZED JAVASCRIPT ORIGINS" and "AUTHORIZED REDIRECT URIS"
    // This will net you the clientId and the clientSecret needed.
    // Also be sure to pass the location as well. It must be in the list of "AUTHORIZED REDIRECT URIS"
    // You must also enable the Google+ API in your profile.
    // Go to APIs & Auth, then APIs and under Social APIs click Google+ API and enable it.


    require('./src/oauth/index')(server);
    
    server.auth.strategy('facebook' ,'bell' ,{
      provider: 'facebook',
      password: 'cookie_encryption_password_secure',
      isSecure: false,
      clientId: '309363739665264',
      clientSecret: '0d6a0cb0eeee4e6064214ed3439875f6',
      location: server.info.uri 
    });

    server.auth.strategy('google', 'bell', {
        provider: 'google',
        password: 'cookie_encryption_password_secure',
        isSecure: false,
        clientId: '656937457543-60putf560cqtqn9g5gv8hpncq5q1taaf.apps.googleusercontent.com',
        clientSecret: 'LrCiWM8omn7f9-y022Uq0JRG',
        location: server.info.uri 
    });
  
    // i want to do like this 
    server.route({
        method: 'POST',
        path: '/signInWithGoogle',
            handler: async function (request, h) {
              console.log(request.payload.access);
              const {res , payload } = await Wreck.get('https://www.googleapis.com/plus/v1/people/me',{
                headers: {
                    'Authorization' : `Bearer ${request.payload.access}`,
                    'content-type': 'application/x-www-form-urlencoded'
                } 
               })
               console.log(payload.toString());
            }
    });
 //instead of doing like this
    server.route({
      method: 'get',
      path: '/signInwithFacebook',
      config: {
          auth: {
              strategy: 'facebook',
              mode: 'try'
          },
          handler: function (request, h) {
              console.log(request.auth);
              if (!request.auth.isAuthenticated) {
                  return h.response('Authentication failed due to: ' + request.auth.error.message);
              }
              return h.response(JSON.stringify(request.auth.credentials, null, 4));
          }
      }
  });

    server.route({
      method: 'GET',
      path: '/',
      handler : (request , h) =>{
        console.log('Sfdhu');
        return h.response('Hello');
      }
  });

  server.route({
    method : 'GET',
    path: '/profile',
    handler : (request , h) => {
      console.log(request.auth);
      return h.response('Hi ');
    }
  })

    await server.start();
    console.log('Server started at:', server.info.uri);
};

internals.start();`

**Comment by hrithick** [comment]
OK There is Three steps in google oauth2 process .
1. take authorization code
2. Exchange authorization code to get access token
3.pass access token to get user info

when i decouple front end and back end . In these three steps what are all i should do in front end and in back-end.
in security aspects ?

**Comment by AdriVanHoudt** [comment]
@hrithick I highly advise you to remove all the tokens and secrets from the initial post and then remove the history (there is like an edited button next to your name above the post).
Also don't use these credentials anywhere anymore, make new ones as they are basically compromised.

Then to your actual question, I will not make any security recommendations here (apart from pointing out your tokens are compromised).
Maybe you can find more info here https://developers.google.com/identity/protocols/OAuth2UserAgent
