### ISSUE TITLE
google login error

### ISSUE THREAD

**Issue by palashg7563** [hapijs/bell#388]
[Link](https://github.com/hapijs/bell/blob/master/examples/google.js)

Just try out the above example 

Configuration for the Client ID and the Client Secret 
Authorized JavaScript origins:
http://localhost:8000

Authorized redirect URIs
http://localhost:8080/bell/door

Got 400 error

**Comment by palashg7563** [comment]
point out... if i have done anything wrong

**Comment by AdriVanHoudt** [comment]
Does the error provide any more information? is this a 400 from Google or your server?

**Comment by palashg7563** [comment]
Actually that not from my server as all config are right

**Comment by AdriVanHoudt** [comment]
If the error comes from Google it must have more info then just 400 no?

**Comment by palashg7563** [comment]
any update @AdriVanHoudt

**Comment by AdriVanHoudt** [comment]
That error means that your server is redirecting to a uri that is not listed in your config for your Google app.
Might be that your server is redirecting to 127.0.0.1 instead of localhost or something. But this means this is not an issue with Bell but with your config.
