### ISSUE TITLE
Upgrade LinkedIn to support new 'Lite Profile'

### ISSUE THREAD

**Issue by dawnerd** [hapijs/bell#390]
Couple small changes LinkedIn is making that need to be accounted for. Mainly:

 - r_liteprofile (replaces r_basicprofile)
 - email no longer part of the profile request

https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context

**Comment by AdriVanHoudt** [comment]
Thanks for letting us know!

I would add
* profile url changed

Are you up for doing a PR? If you need any help or have any questions, just let us know.

**Comment by AdriVanHoudt** [comment]
Awesome 💪
