### ISSUE TITLE
Google auth redirect loop with hapi v18

### ISSUE THREAD

**Issue by JoshGlazebrook** [hapijs/bell#394]
Upgrading from v17.8.1 -> v18.0.0 seems to cause a redirect loop. Following the same exact configuration pattern as https://github.com/hapijs/bell/blob/master/examples/google.js

My router handler is never actually called, instead the route is redirected to the google SSO login page, and when the correct google account is selected, it redirects back, but the handler is never called. Instead it redirects back to Google. Downgrading to 17.8.1 it works fine.

**Comment by chrisshiplet** [comment]
Also seeing this with the FB provider. From what I can tell when the OAuth client code gets to here: https://github.com/hapijs/bell/blob/master/lib/oauth.js#L176

`request.query` is set to `{}` even when the raw URL in the request object shows `?code=whatever` in the URL string. I don't have more time today to dig into this

**Comment by framerate** [comment]
I'm seeing this behavior too on my first time using Bell. Is it looking like a module error or user error?

**Comment by AdriVanHoudt** [comment]
I can confirm this is happening with hapi@18 🙊
It seems that the cookie (in my case bell-google) is not there when the flow comes back from the google oauth flow to bell.
Running the tests under hapi@18 breaks a lot of them, most of them due to the redirect not adding a port anymore. I have not figured out why but I will look at this tonight.

**Comment by pdxmholmes** [comment]
I'm seeing the same issue with the Twitch provider. I've rolled back to Hapi@17 for now and the problem goes away.

**Comment by AdriVanHoudt** [comment]
I think this is an issue with just the oAuth flow code and hapi@18.
I'm still looking into it but if you want to help -> `npm i hapi@18 && npm t` to see what is currently failing for hapi@18 :D

**Comment by pdxmholmes** [comment]
Some of the errors appear to be because of a change to server.inject in hapi@18. Specifically it seems to eat the port now if it's port 80 (and I assume 443 though I haven't tested it). That doesn't explain the loop being caused in real code, but does cover some of the broken tests.
