### ISSUE TITLE
Safari isSameSite

### ISSUE THREAD

**Issue by flipxfx** [hapijs/bell#395]
I'm having redirect loops upon trying to login with Okta in Safari. I noticed that if I manually change `isSameSite` to `'Lax'` or `false` in the `cookieOptions` for bell it fixes the issue. 

Bell: 9.4.0
Hapi: 18.1.0
Hapi auth cookie: 9.1.0
Safari: 12.0.2

**Comment by flipxfx** [comment]
Seems like it might be related to https://bugs.webkit.org/show_bug.cgi?id=188165.

Possibly just adding the ability to change this setting similar to how bell allows changing `isSecure` and `isHttpOnly` would be useful.

**Comment by flipxfx** [comment]
@hueniverse This is effecting production stuff as it's related to Safari breaking something. Can we get this looked at soon? I submitted a merge request that could at least fix the problem for now by adding the ability to customize the cookie `isSameSite`.

**Comment by hueniverse** [comment]
@AdriVanHoudt Got time to review and merge?
