### ISSUE TITLE
Forcing redirect_uri to be https

### ISSUE THREAD

**Issue by briandela** [hapijs/bell#40]
Just wondering if it's possible to force to `redirect_uri` to be https. We're deploying hapi on Heroku and heroku does SSL termination at the edge of their network. This means we run hapi as http. Bell seems to take the protocol the site is running as and make that the protocol for the redirect_uri - this causes an issue when the provider (e.g. facebook) redirect back to our site as it comes back as http instead of https.

I couldn't see in the options a way to tell bell to use https for the redirect_uri protocol. Just wondering if there is a work around for the moment.

**Comment by petehunt** [comment]
+1, every app server deployment I've worked with terminates SSL with nginx

**Comment by eiriksm** [comment]
+1 from me. Had me wondering for a while. Would a PR implementing this as an option be considered?

**Comment by eiriksm** [comment]
Instead of waiting for an answer to that, I went ahead and submitted the PR over at #53

**Comment by ericeslinger** [comment]
This doesn't seem to work yet- I tried bell 2.1.0 with forceHttps: true, and bell threw 500 errors with "redirect_uri_mismatch" responses, which seem to be coming off of the google endpoint.

I rolled back to bell 2.0.0 and used @fampinheiro 's workaround, and it seems to work. In earlier versions (hapi 7.5), I was able to just set the location parameter on the server, and bell seemed to pick it up. However, hapi 8.0 dropped support for location, and setting uri at server creation doesn't seem to work.

I'll spend some time tomorrow actually diagnosing the problem, tonight I'm just too worn out from chasing this down- we're upgrading our beta servers from the hapi 7 to 8 version, and I thought I had everything, but https is one of those things you don't really notice on your typical dev laptop.

**Comment by KrisSiegel** [comment]
I'm having the exact same issue as @ericeslinger; I upgraded to 2.1.0 but whenever forceHttps is being used google returns "redirect_uri_mismatch". If I find a cause in bell I'll report back as this is something I'm actively debugging.

**Comment by KrisSiegel** [comment]
Okay yeah the internals.location method is used in several places but in the PR it's not updated in every place to use the protocol (which may be a forced https). As a debug step I simply updated internals.location to do this and it worked perfectly:
```
internals.location = function (request, protocol) {
    return "https://<myhost>/auth/google";
    var info = request.connection.info;
    protocol = protocol || info.protocol;
    var host = request.info.host || (info.host + ':' + info.port);
    return protocol + '://' + host + request.path;
};
```
So I went ahead, forked bell, added the fix and verified it in my own deployment on one of our development instances. Seems to be working as expected so I'll submit a PR (it's a pretty minor change).

**Comment by KrisSiegel** [comment]
Looks like #60 really fixed it, not my #61. I just deployed and verified that it looks good on our development server with SSL.

**Comment by ericeslinger** [comment]
Ah, good to know. I will test 2.2.0 on my beta server.

**Comment by brand7n** [comment]
My suggestion would be something like this for people already using the old server location setting:  https://github.com/hapijs/bell/compare/master...brand7n:master
