### ISSUE TITLE
Passing Scope

### ISSUE THREAD

**Issue by imcodingideas** [hapijs/bell#401]
Inside `/lib/providers/slack.js#L24` I need to be able to pass a different scope to profile.

        profile: async function (credentials, params, get) {

            credentials.profile = {
                access_token: params.access_token,
                scope: params.scope
            };
        }

Any user who is not an admin seems to be getting:         `scope: ['identify'],                                    // Minimum scope required to identify the user` and admins are getting the proper scope. 

This means I need to pass it.. in my case: `scope: ['identify', 'groups:read', 'channels:read', 'im:read', 'mpim:read', 'users:read', 'users:read.email', 'users.profile:read']`

https://github.com/hapijs/bell/blob/master/examples/slack.js

How do I pass the scope to the function?

**Comment by imcodingideas** [comment]
@AdriVanHoudt is there any thing I can to help?

**Comment by AdriVanHoudt** [comment]
Where you pass your config to `server.auth.strategy` you can set the `scope` to what you want. See https://github.com/hapijs/bell/blob/master/API.md#options

**Comment by hueniverse** [comment]
If someone wants to improve the docs, I'll merge.
