### ISSUE TITLE
Can Bell integrate with AWS Cognito?

### ISSUE THREAD

**Issue by EyePulp** [hapijs/bell#408]
I know this is a pretty basic question, but my auth knowledge is pretty limited.  I'm trying to figure out the most hapi-centric method for integrating with AWS Cognito User Pools.  I believe it's OAuth 1.0 and 2.0 capable, so I'm trying to figure out if that's a usable provider for bell.

Thanks!

**Comment by hueniverse** [comment]
If by "integrate" you mean use it as a third-party login provider, sure. But if you are just looking for an OAuth client to make direct calls to their API, then it could work but more use other OAuth libraries for that.

**Comment by EyePulp** [comment]
Thanks for the guidance @hueniverse
