### ISSUE TITLE
Bell + Keycloak (openid-connect)

### ISSUE THREAD

**Issue by sscarduzio** [hapijs/bell#417]
Sorry if this is a basic question, but: if I use Bell authentication strategy, will users be able to login into my web app via a Keycloak server configured as "openid-connect"?

If yes, is there any example I should refer to?

Thanks!

**Comment by hueniverse** [comment]
It just provides an oauth 1 and 2 implementation that you can configure with any compatible provider. It also provides a list of preconfigured providers. So the answer is yes. I recommend trying the provided examples to get a feel for it.
