### ISSUE TITLE
Replace office365, azuread with updated azure provider

### ISSUE THREAD

**Issue by hueniverse** [hapijs/bell#427]

**Comment by teddmason** [comment]
@hueniverse Hi Eran, this change has broken our azureAD authentication, the microsoft graph api (https://graph.microsoft.com/v1.0/me) doesn't expose user application roles, and my provider has said that the graph api is locked down in production so is a non starter for us.

Is there a reason for ditching the old endpoint https://login.microsoftonline.com/defrasandpit.onmicrosoft.com/openid/userinfo ?

**Comment by hueniverse** [comment]
Which provider do you want to see reintroduced? I can add it as -legacy as long as it is not deprecated by MS.

**Comment by teddmason** [comment]
azuread is what we use in v10 and it is not being deprecated... as far as I'm aware, thanks
