### ISSUE TITLE
How to get facebook profile picture with custom size?

### ISSUE THREAD

**Issue by hbinduni** [hapijs/bell#442]
I am trying to get facebook profile with custom size. right now, by default if we use facebook, it will return profile with 50x50. But how to get the same profile with custom size? like 100x100.

i know i can do another query to facebook something like this:
```
https://graph.facebook.com/v4.0/user-id-xxx/picture?type=normal&access_token=xxx
```

but i think that is not proper solution. maybe using `profileParams` [API](https://github.com/hapijs/bell/blob/master/API.md) but not sure.
please help. thank you.

**Comment by hueniverse** [comment]
Closed because you ignored the issue template.
