### ISSUE TITLE
How to get facebook profile picture with custom size?

### ISSUE THREAD

**Issue by hbinduni** [hapijs/bell#443]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v10.16.3
* *module version*: ^11.1.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### How can we help?

I am trying to get facebook profile with custom size. right now, by default if we use facebook, it will return profile with 50x50. But how to get the same profile with custom size? like 100x100.

i know i can do another query to facebook something like this:

```js
https://graph.facebook.com/v4.0/user-id-xxx/picture?type=normal&access_token=xxx
```
but i think that is not proper solution. maybe using `profileParams` [API](https://github.com/hapijs/bell/blob/master/API.md) but not sure.
please help. thank you.

**Comment by hueniverse** [comment]
The default fields bell requests from Facebook are: `'id,name,email,first_name,last_name,middle_name,picture,gender,link,locale,timezone,updated_time,verified'`. I took a quick look at the FB API docs but could not find a flag or field that can change the type of picture provided. If you can figure out a way to get the profile picture you want with the /me API, let me know and I can help you figure out how to get it directly from bell.

**Comment by hbinduni** [comment]
i can get another profile image size using this query:
```
curl -X GET \
  'https://graph.facebook.com/v4.0/user-id-here/picture?type=normal&access_token=access-token-here' \
```

more documentation can be found here:

[facebook user picture](https://developers.facebook.com/docs/graph-api/reference/user/picture/)

**Comment by hbinduni** [comment]
why this being closed? i still hope to get a better way to do this using bell API.

**Comment by hueniverse** [comment]
Did you read my reply? I can't find a better way because the FB API used for profile doesn't seem to have that option. I told you that if you find such a way with the API we use, we can figure it out. You just repeated the same information again.

**Comment by hbinduni** [comment]
i see. thank you
