### ISSUE TITLE
Improve the debugging experience when a payload is involved

### ISSUE THREAD

**Issue by k3n** [hapijs/bell#471]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12
* *module version*: 10.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: salesforce oauth2

#### What problem are you trying to solve?

The `payload` is still a `Buffer` when it's passed to `Boom`; if parsed, then the error would've been front & center and saved a lot of time.

```
{ Error: Failed obtaining custom access token
    at Object.authenticate (/Users/k3n/code/project/node_modules/bell/lib/oauth.js:276:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  data:
   <Buffer 54 68 65 ... >,
```

The error here (captured in the `payload`) was:

```html
The URL has moved <a href "https://instance.my.salesforce.com/services/oauth2/token">here</a>\r\n
```

#### Do you have a new or modified API suggestion to solve the problem?

Other than parsing the `payload` before passing it to `Boom`, no.

**Comment by Nargonath** [comment]
Would you mind sharing a reproduction test, please?
