### ISSUE TITLE
Support client credentials as functions

### ISSUE THREAD

**Issue by jonathansamines** [hapijs/bell#475]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: v12.19.1
* *module version*: v12.1.1
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi
* *any other relevant information*: -

#### What problem are you trying to solve?

At our organization, we automatically create client credentials at application startup (only on dev and test environments). We do that by using a hapi plugin that creates those credentials at the `onPreStart` hook. Credentials can be accessed at any time, but they are only really available at startup.

Now, while trying to integrate bell with that plugin, I ran into an interesting limitation. Because credentials are created at startup time and authentication strategies are usually registered before that, by the time the authentication strategy is created I don't (yet) have the credentials available. 

```js
'use strict';

const Hapi = require('@hapi/hapi');
const Credentials = require('some-credentials-plugin');
const Bell = require('@hapi/bell');

async function run() {
  const server = Hapi.server();

  await server.register([
    Bell,
    {
      plugin: Credentials,
      options: {
        type: 'the-client-type',
        scopes: ['scope-a']
      },
    },
  ]);

  // at this point we need the client credentials
  server.auth.strategy('third-party', 'bell', {});

  server.route({
    path: '/login',
    method: ['GET', 'POST'],
    options: {
      auth: 'third-party',
      handler() {
         return 'welcome';
      }
    },
  });

  await server.initialize();

  // I have the application credentials at this point, but it is too late
  // trying to access them before the server is initialized would cause an error throw inside the `get` method
  const credentials = server.plugins.credentials.get('the-client-type');
}
```

#### Do you have a new or modified API suggestion to solve the problem?
Bell does not need the application credentials at startup, it needs them only when a request is processed (at least for OAuth 2.0). If if were possible to specify credentials as functions, we would solve the problem because by the time those functions are invoked those credentials would be already available.

```js
  server.auth.strategy('third-party', 'bell', {
    clientId() {
      return server.plugins.credentials.get('the-client-type').clientId;
    },
    clientSecret() {
      return server.plugins.credentials.get('the-clien-type').clientSecret,
    },
  });
```

**Comment by Nargonath** [comment]
I'm not well-versed with bell mecanism but it seems like a reasonable feature to me.

**Comment by jonathansamines** [comment]
After some researching I found a different solution to this problem by using `server.dependency()`:

```javascript
'use strict';

const Hapi = require('@hapi/hapi');
const Credentials = require('some-credentials-plugin');
const Bell = require('@hapi/bell');

const Routes = {
  name: 'routes',
  register(server) {
    server.dependency('some-credentials-plugin', (srv) => {
      // at this point credentials are already available because server has already been initialized
      const credentials = server.plugins.credentials.get('the-client-type');
      srv.auth.strategy('third-party', 'bell', credentials);

      srv.route({
        path: '/login',
        method: ['GET', 'POST'],
        options: {
          auth: 'third-party',
          handler() {
            return 'welcome';
          },
        },
      });
    });
  },
};

async function run() {
  const server = Hapi.server();
  await server.register([
    Bell,
    Routes,
    {
      plugin: Credentials,
      options: {
        type: 'the-client-type',
        scopes: ['scope-a'],
      },
    },
  ]);

  await server.initialize();
}
```

As usual, the framework is always as flexible as one would wish!

**Comment by Nargonath** [comment]
That's a nifty solution @jonathansamines. Well done!
