### ISSUE TITLE
redirected url querystring in protected routes 

### ISSUE THREAD

**Issue by smitp** [hapijs/bell#51]
After successfull authentication, querystring are not retained for protected routes.

Ex. For route `/auth/login/twitter` protected with `twitter` auth strategy in `required` mode
URL `/auth/login/twitter?next=%2F/home` redirects to `/auth/login/twitter` after authenticated successfully. Should it retain query params in redirected url after authenticated?
Is this valid behavior? If not, how we achieve it by using temporary state between the authorization flow?

**Comment by silas** [comment]
Take a look at `request.auth.credentials.query`, it should have the original query parameters.

**Comment by smitp** [comment]
Thanks @silas. That helps a lot.
