### ISSUE TITLE
Question about reply.redirect call at oauth.js

### ISSUE THREAD

**Issue by luciano-junior** [hapijs/bell#56]
Hi!

I would like to question about this redirection [here](https://github.com/hapijs/bell/blob/220b5d527ac678cec9222f78b08bb4bb83511372/lib/oauth.js#L163)

When this redirection is done, the client gets notified of two parameters: **code** and **state**. However, these parameters should concern just the server, right? Does the client need to know any of these information?

Do my questions make any sense? Could it be a vulnerability?

For example, according to the [facebook documentation](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/v2.2), I can exchange **code** for an access token.

First. I would like know if I really should worry about the fact of the client knowing about the **code** and **state** parameters.

Second. How could we avoid this redirection in order not to get the user notified about information that should concern just the server?

Finally. Thank you so much for building hapi.js and bell :)

**Comment by jaw187** [comment]
No, it is not a vulnerability.  The parameters are used in combination with a client secret which will ensure a secure exchange.

1. No, you should not worry about the client knowing the parameters.  The parameters are used in combination with a client secret which will ensure a secure exchange.

2. Without redirects, your server would have to collect login information and it would nullify the need for Bell/OAuth.
