### ISSUE TITLE
Deprecated Google and Facebook APIs

### ISSUE THREAD

**Issue by ulrik59** [hapijs/bell#66]
Hi everyone,

I'm actually using Bell for Facebook and Google without any problem but I noticed that used API for both providers are deprecated.
Here's the documentation about Google: https://developers.google.com/accounts/docs/OAuth2LoginV1
And Facebook send this warning when I want to authenticate: 
![deprecatedfacebook](https://cloud.githubusercontent.com/assets/6003644/6968793/adb6450a-d969-11e4-9164-026109a3387f.jpg)

Is there any plan to update Facebook and Google providers code ?
Thank you

**Comment by geek** [comment]
Thanks.  We definitely need to fix that if there is an updated API we should be using.

**Comment by geek** [comment]
The Facebook issue is fixed in 2.4.0

**Comment by geek** [comment]
Google is fixed by https://github.com/hapijs/bell/pull/108 in bell v5.0.0
