### ISSUE TITLE
No 'access-control-allow-origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by mazzy89** [hapijs/bell#74]
I'm using bell at the server side while at the client side I'm using Angular. I call the /auth/facebook entrypoint at the server side by using $http but I get the error

```
No 'access-control-allow-origin' header is present on the requested resource.
```

Have you any  suggestions how to use bell with angularjs frontend?

**Comment by ldesplat** [comment]
Do you still need help with such an issue? 

CORS Documentation: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
Hapi and CORS: http://hapijs.com/api#route-options (scroll down to cors)
