### ISSUE TITLE
facebook expiration won't be mapped properly

### ISSUE THREAD

**Issue by StephanGerbeth** [hapijs/bell#89]
Hi,

actually the expiration date of facebook access token won't be mapped properly.

You implemented a default mapping:
oauth.js - line 229: `expiresIn: payload.expires_in`

but the facebook payload attribute is called 'expires' only.

Cheers
Stephan

**Comment by diego04** [comment]
Im having issues with facebook expiraton as well. request.auth.credentials.expiresIn, this is undefined

**Comment by ldesplat** [comment]
Anybody want to submit a PR?

Also, the spec specifies `expires_in` so I am surprised facebook is doing that. If the PR upgrades to the latest API and this still happens I could take a PR that fixes it.

**Comment by ldesplat** [comment]
This should work now as of 5.0.1. We were not using the most up to date API endpoint.
